window.ETO_ACADEMY = {
  ui: {
    ru: {
      brand:'Это сложнее', home:'Главная', learn:'Учиться', map:'Карта знаний', daily:'Сегодня', simulator:'Симулятор', progress:'Прогресс', library:'Библиотека', games:'Игры', glossary:'Словарь', menu:'Меню', theme:'Тема', language:'Язык',
      learnEyebrow:'МИНИ-КУРСЫ', learnTitle:'Учись короткими маршрутами.', learnText:'Каждый маршрут соединяет факты, терминологию, маленькие проверки и практику. Прогресс хранится только в этом браузере.', start:'Начать', continue:'Продолжить', completed:'Пройдено', lesson:'урок', lessons:'уроков', checkpoint:'Проверка', markDone:'Отметить как изученное', done:'Изучено', resetCourse:'Сбросить курс',
      mapEyebrow:'КАРТА ЗНАНИЙ', mapTitle:'Увидь, как темы связаны.', mapText:'Нажимай на узлы: от статистики риска к дизайну исследований, мозгу и веществам. Линии показывают смысловые связи, а не причинность.', open:'Открыть', filterAll:'Все', filterStats:'Статистика', filterDesign:'Дизайн', filterBrain:'Мозг', filterSubstances:'Вещества',
      dailyEyebrow:'ЕЖЕДНЕВНЫЙ CHALLENGE', dailyTitle:'Один вопрос в день.', dailyText:'Короткая задача на интерпретацию данных. Новый вопрос определяется календарной датой и одинаков для всех пользователей.', answer:'Ответить', correct:'Верно', incorrect:'Не совсем', explanation:'Почему', comeBack:'Следующий challenge будет завтра.', streak:'Серия', days:'дн.',
      simEyebrow:'СИМУЛЯТОР ИССЛЕДОВАНИЯ', simTitle:'Собери исследование — и посмотри, что ты сломал.', simText:'Это учебная модель. Ты выбираешь дизайн, выборку, измерение и анализ; симулятор показывает типичные угрозы валидности.', step:'Шаг', next:'Дальше', back:'Назад', finish:'Получить разбор', restart:'Начать заново', score:'Качество дизайна', strong:'Сильная сторона', risk:'Риск', recommendation:'Что улучшить',
      progressEyebrow:'ТВОЙ ПРОГРЕСС', progressTitle:'Что уже усвоено — и что пора повторить.', progressText:'Без аккаунта: данные сохраняются локально в браузере. Можно очистить в любой момент.', cardsAnswered:'Карточек отвечено', cardsCorrect:'Правильных ответов', coursesDone:'Уроков пройдено', dailyDone:'Daily challenge', due:'Пора повторить', review:'Повторить', noReview:'Пока нечего повторять. Ответь на несколько карточек или пройди курс.', clearProgress:'Очистить прогресс', clearConfirm:'Удалить весь локальный прогресс?', accuracy:'Точность',
      privacy:'Прогресс не отправляется на сервер: хранится только в localStorage этого браузера.'
    },
    en: {
      brand:'It’s more complicated', home:'Home', learn:'Learn', map:'Knowledge map', daily:'Today', simulator:'Simulator', progress:'Progress', library:'Library', games:'Games', glossary:'Glossary', menu:'Menu', theme:'Theme', language:'Language',
      learnEyebrow:'MINI-COURSES', learnTitle:'Learn in short guided paths.', learnText:'Each path connects facts, terminology, quick checks and practice. Progress is stored only in this browser.', start:'Start', continue:'Continue', completed:'Completed', lesson:'lesson', lessons:'lessons', checkpoint:'Checkpoint', markDone:'Mark as learned', done:'Learned', resetCourse:'Reset course',
      mapEyebrow:'KNOWLEDGE MAP', mapTitle:'See how the ideas connect.', mapText:'Tap nodes to move from risk statistics to study design, the brain and substances. Lines indicate conceptual links, not causality.', open:'Open', filterAll:'All', filterStats:'Statistics', filterDesign:'Design', filterBrain:'Brain', filterSubstances:'Substances',
      dailyEyebrow:'DAILY CHALLENGE', dailyTitle:'One question a day.', dailyText:'A short task about interpreting evidence. The calendar date determines the question, so everyone gets the same one.', answer:'Answer', correct:'Correct', incorrect:'Not quite', explanation:'Why', comeBack:'The next challenge arrives tomorrow.', streak:'Streak', days:'days',
      simEyebrow:'STUDY SIMULATOR', simTitle:'Build a study — then see what you broke.', simText:'This is a learning model. Choose design, sampling, measurement and analysis; the simulator highlights common threats to validity.', step:'Step', next:'Next', back:'Back', finish:'Show review', restart:'Start over', score:'Design quality', strong:'Strength', risk:'Risk', recommendation:'Improve it',
      progressEyebrow:'YOUR PROGRESS', progressTitle:'What you know — and what is due for review.', progressText:'No account required: data is stored locally in this browser and can be cleared anytime.', cardsAnswered:'Cards answered', cardsCorrect:'Correct answers', coursesDone:'Lessons completed', dailyDone:'Daily challenge', due:'Due for review', review:'Review', noReview:'Nothing is due yet. Answer some cards or start a course.', clearProgress:'Clear progress', clearConfirm:'Delete all local learning progress?', accuracy:'Accuracy',
      privacy:'Progress is not sent to a server; it stays in this browser’s localStorage.'
    },
    et: {
      brand:'See on keerulisem', home:'Avaleht', learn:'Õpi', map:'Teadmiste kaart', daily:'Täna', simulator:'Simulaator', progress:'Edenemine', library:'Teek', games:'Mängud', glossary:'Sõnastik', menu:'Menüü', theme:'Teema', language:'Keel',
      learnEyebrow:'MINIKURSUSED', learnTitle:'Õpi lühikeste juhitud radade kaudu.', learnText:'Iga rada ühendab faktid, terminid, lühikontrollid ja praktika. Edenemine salvestatakse ainult selles brauseris.', start:'Alusta', continue:'Jätka', completed:'Läbitud', lesson:'õppetund', lessons:'õppetundi', checkpoint:'Kontroll', markDone:'Märgi õpituks', done:'Õpitud', resetCourse:'Lähtesta kursus',
      mapEyebrow:'TEADMISTE KAART', mapTitle:'Vaata, kuidas ideed seostuvad.', mapText:'Puuduta sõlmi: liigu riskistatistikast uuringudisaini, aju ja ainete juurde. Jooned näitavad mõistelisi seoseid, mitte põhjuslikkust.', open:'Ava', filterAll:'Kõik', filterStats:'Statistika', filterDesign:'Disain', filterBrain:'Aju', filterSubstances:'Ained',
      dailyEyebrow:'PÄEVA VÄLJAKUTSE', dailyTitle:'Üks küsimus päevas.', dailyText:'Lühike ülesanne tõendusmaterjali tõlgendamisest. Küsimuse määrab kuupäev ning see on kõigile sama.', answer:'Vasta', correct:'Õige', incorrect:'Mitte päris', explanation:'Miks', comeBack:'Järgmine väljakutse tuleb homme.', streak:'Seeria', days:'päeva',
      simEyebrow:'UURINGUSIMULAATOR', simTitle:'Ehita uuring — ja vaata, mida rikkusid.', simText:'See on õpimudel. Vali disain, valim, mõõtmine ja analüüs; simulaator näitab levinud valiidsusohte.', step:'Samm', next:'Edasi', back:'Tagasi', finish:'Näita analüüsi', restart:'Alusta uuesti', score:'Disaini kvaliteet', strong:'Tugevus', risk:'Risk', recommendation:'Paranda',
      progressEyebrow:'SINU EDENEMINE', progressTitle:'Mida sa juba tead — ja mida tasub korrata.', progressText:'Kontot pole vaja: andmed salvestatakse lokaalselt selles brauseris ja neid saab igal ajal kustutada.', cardsAnswered:'Vastatud kaarte', cardsCorrect:'Õigeid vastuseid', coursesDone:'Läbitud õppetunde', dailyDone:'Päeva väljakutse', due:'Kordamiseks valmis', review:'Korda', noReview:'Praegu pole midagi korrata. Vasta mõnele kaardile või alusta kursust.', clearProgress:'Kustuta edenemine', clearConfirm:'Kas kustutada kogu kohalik õpiedu?', accuracy:'Täpsus',
      privacy:'Edenemist ei saadeta serverisse; see jääb selle brauseri localStorage’i.'
    }
  },
  courses: [
    {id:'risk-basics', icon:'%', color:'stats', title:{ru:'Как читать риск',en:'How to read risk',et:'Kuidas riski lugeda'}, desc:{ru:'Абсолютный риск, RR, OR и почему громкий процент может вводить в заблуждение.',en:'Absolute risk, RR, OR, and why a dramatic percentage can mislead.',et:'Absoluutne risk, RR, OR ja miks suur protsent võib eksitada.'}, lessons:[
      {id:'relative-absolute', title:{ru:'Относительное и абсолютное',en:'Relative vs absolute',et:'Suhteline vs absoluutne'}, body:{ru:'Один и тот же относительный эффект может означать совершенно разное абсолютное изменение. Всегда спроси: от какого исходного риска считаем?',en:'The same relative effect can correspond to very different absolute changes. Always ask: relative to what baseline risk?',et:'Sama suhteline mõju võib tähendada väga erinevat absoluutset muutust. Küsi alati: millise algriski suhtes?'}},
      {id:'odds-ratio', title:{ru:'OR — не процент',en:'OR is not a percentage',et:'OR ei ole protsent'}, body:{ru:'Odds ratio сравнивает шансы, а не напрямую вероятности. При частых исходах OR и RR могут заметно расходиться.',en:'An odds ratio compares odds, not probabilities directly. For common outcomes OR and RR can diverge substantially.',et:'Odds ratio võrdleb šansse, mitte otseselt tõenäosusi. Sagedaste tulemuste korral võivad OR ja RR märgatavalt erineda.'}},
      {id:'uncertainty', title:{ru:'Оценка без неопределённости неполна',en:'An estimate without uncertainty is incomplete',et:'Hinnang ilma ebakindluseta on puudulik'}, body:{ru:'Точечная оценка должна читаться вместе с доверительным интервалом, дизайном и размером выборки.',en:'A point estimate should be read alongside its confidence interval, design and sample size.',et:'Punktihinnangut tuleb lugeda koos usaldusvahemiku, disaini ja valimi suurusega.'}}
    ]},
    {id:'study-design', icon:'⌕', color:'design', title:{ru:'Детектив исследования',en:'Study detective',et:'Uuringudetektiiv'}, desc:{ru:'Как распознавать confounding, selection bias, recall bias и проблемы переносимости.',en:'Spot confounding, selection bias, recall bias and generalisability problems.',et:'Õpi märkama segavaid tegureid, valikukallutatust, meenutusvigu ja üldistatavuse probleeme.'}, lessons:[
      {id:'association', title:{ru:'Ассоциация не равна причинности',en:'Association is not causation',et:'Seos ei võrdu põhjuslikkusega'}, body:{ru:'Связь может возникать из-за причинности, обратной причинности, смешения или систематической ошибки.',en:'An association may reflect causation, reverse causation, confounding or systematic error.',et:'Seos võib tuleneda põhjuslikkusest, vastupidisest põhjuslikkusest, segavatest teguritest või süstemaatilisest veast.'}},
      {id:'selection', title:{ru:'Кто попал в выборку?',en:'Who entered the sample?',et:'Kes valimisse sattus?'}, body:{ru:'Если механизм попадания в исследование связан с воздействием и исходом, оценка может систематически сместиться.',en:'If study inclusion is related to exposure and outcome, the estimate may become systematically biased.',et:'Kui uuringusse sattumine on seotud nii kokkupuute kui tulemusega, võib hinnang süstemaatiliselt nihkuda.'}},
      {id:'generalise', title:{ru:'К кому применим результат?',en:'Who does the result apply to?',et:'Kellele tulemus kehtib?'}, body:{ru:'Даже внутренне валидное исследование не обязано переноситься на другой возраст, дозу, страну или клиническую ситуацию.',en:'Even an internally valid study may not generalise to another age, dose, country or clinical setting.',et:'Isegi sisemiselt valiidne uuring ei pruugi üldistuda teisele vanusele, annusele, riigile või kliinilisele olukorrale.'}}
    ]},
    {id:'substances', icon:'◉', color:'substances', title:{ru:'Вещества без рейтинга “что хуже”',en:'Substances without a “worst” ranking',et:'Ained ilma “mis on halvim” pingereata'}, desc:{ru:'Разделяем зависимость, токсичность, психические риски, отмену и общественный вред.',en:'Separate dependence, toxicity, psychiatric risk, withdrawal and population harm.',et:'Erista sõltuvus, toksilisus, psühhiaatriline risk, võõrutus ja rahvastikukahju.'}, lessons:[
      {id:'dimensions', title:{ru:'Вред многомерен',en:'Harm is multidimensional',et:'Kahju on mitmemõõtmeline'}, body:{ru:'Сравнение веществ зависит от того, сравниваем ли мы смертность, зависимость, канцерогенность, психические исходы, аварии или общественный вред.',en:'Substance comparisons depend on whether we mean mortality, dependence, carcinogenicity, psychiatric outcomes, crashes or societal harm.',et:'Ainete võrdlus sõltub sellest, kas räägime suremusest, sõltuvusest, kantserogeensusest, psühhiaatrilistest tulemustest, õnnetustest või ühiskondlikust kahjust.'}},
      {id:'route', title:{ru:'Молекула и способ доставки — не одно',en:'Molecule and delivery route are not the same',et:'Molekul ja manustamisviis pole sama'}, body:{ru:'Например, значительная часть вреда сигарет связана с продуктами горения, а никотин играет ключевую роль в зависимости.',en:'For example, much cigarette harm comes from combustion products, while nicotine is central to dependence.',et:'Näiteks suur osa sigarettide kahjust tuleneb põlemisproduktidest, samas kui nikotiinil on keskne roll sõltuvuses.'}},
      {id:'context', title:{ru:'Доза, продукт и контекст меняют вывод',en:'Dose, product and context change the conclusion',et:'Annus, toode ja kontekst muudavad järeldust'}, body:{ru:'“Каннабис”, “алкоголь” или “никотин” — слишком широкие ярлыки без дозы, частоты, крепости/потентности и популяции.',en:'“Cannabis”, “alcohol” or “nicotine” are broad labels without dose, frequency, potency and population context.',et:'“Kanep”, “alkohol” või “nikotiin” on liiga laiad sildid ilma annuse, sageduse, tugevuse ja populatsiooni kontekstita.'}}
    ]}
  ],
  nodes: [
    {id:'absolute-risk', group:'stats', x:14,y:22,label:{ru:'Абсолютный риск',en:'Absolute risk',et:'Absoluutne risk'},desc:{ru:'Сколько исходов реально ожидается в группе.',en:'How many outcomes are actually expected in a group.',et:'Kui palju tulemusi rühmas tegelikult oodatakse.'},href:'fact.html?id=relative-absolute'},
    {id:'rr', group:'stats', x:35,y:13,label:{ru:'RR',en:'RR',et:'RR'},desc:{ru:'Отношение рисков между двумя группами.',en:'Ratio of risks between two groups.',et:'Riskide suhe kahe rühma vahel.'},href:'games.html#risk-lab'},
    {id:'or', group:'stats', x:54,y:26,label:{ru:'Odds ratio',en:'Odds ratio',et:'Odds ratio'},desc:{ru:'Отношение шансов, а не вероятность.',en:'A ratio of odds, not a probability.',et:'Šansside suhe, mitte tõenäosus.'},href:'games.html#odds-lab'},
    {id:'ci', group:'stats', x:76,y:15,label:{ru:'Доверительный интервал',en:'Confidence interval',et:'Usaldusvahemik'},desc:{ru:'Показывает статистическую неопределённость процедуры оценки.',en:'Expresses statistical uncertainty in the estimation procedure.',et:'Väljendab hinnangu statistilist ebakindlust.'},href:'fact.html?id=confidence-interval'},
    {id:'causality', group:'design', x:24,y:50,label:{ru:'Причинность',en:'Causality',et:'Põhjuslikkus'},desc:{ru:'Как перейти от связи к причинному выводу.',en:'How to move from association to a causal claim.',et:'Kuidas liikuda seosest põhjusliku väiteni.'},href:'fact.html?id=association-causation'},
    {id:'confounding', group:'design', x:49,y:53,label:{ru:'Confounding',en:'Confounding',et:'Segavad tegurid'},desc:{ru:'Третьи факторы могут искажать наблюдаемую связь.',en:'Third variables can distort an observed association.',et:'Kolmandad tegurid võivad nähtavat seost moonutada.'},href:'games.html#bias-detective'},
    {id:'rct', group:'design', x:73,y:48,label:{ru:'RCT',en:'RCT',et:'RCT'},desc:{ru:'Рандомизация помогает внутренней валидности, но не гарантирует переносимость.',en:'Randomisation supports internal validity but does not guarantee generalisability.',et:'Randomiseerimine toetab sisemist valiidsust, kuid ei taga üldistatavust.'},href:'fact.html?id=rct-generalizability'},
    {id:'memory', group:'brain', x:18,y:79,label:{ru:'Память',en:'Memory',et:'Mälu'},desc:{ru:'Воспоминание реконструируется и зависит от контекста извлечения.',en:'Memory is reconstructive and sensitive to retrieval context.',et:'Mälu on rekonstruktiivne ja sõltub meenutamise kontekstist.'},href:'fact.html?id=memory-wording'},
    {id:'sleep', group:'brain', x:43,y:84,label:{ru:'Сон',en:'Sleep',et:'Uni'},desc:{ru:'Ограничение сна может накапливать когнитивные дефициты.',en:'Sleep restriction can accumulate cognitive deficits.',et:'Une piiramine võib kuhjata kognitiivseid puudujääke.'},href:'fact.html?id=sleep-debt'},
    {id:'alcohol', group:'substances', x:66,y:76,label:{ru:'Алкоголь',en:'Alcohol',et:'Alkohol'},desc:{ru:'Канцерогенность, отмена, популяционный вред.',en:'Carcinogenicity, withdrawal and population harm.',et:'Kantserogeensus, võõrutus ja rahvastikukahju.'},href:'fact.html?id=alcohol-cancer'},
    {id:'cannabis', group:'substances', x:86,y:69,label:{ru:'Каннабис',en:'Cannabis',et:'Kanep'},desc:{ru:'Потентность, частота, психоз и вождение.',en:'Potency, frequency, psychosis and driving.',et:'Tugevus, sagedus, psühhoos ja autojuhtimine.'},href:'fact.html?id=cannabis-psychosis'}
  ],
  edges:[['absolute-risk','rr'],['rr','or'],['or','ci'],['absolute-risk','causality'],['rr','confounding'],['or','confounding'],['ci','rct'],['causality','confounding'],['confounding','rct'],['causality','memory'],['confounding','sleep'],['confounding','alcohol'],['rct','alcohol'],['confounding','cannabis'],['sleep','cannabis'],['alcohol','cannabis']],
  daily: [
    {q:{ru:'Исследование сообщает: RR = 2.0. Исходный риск — 1 на 1000. Какой приблизительно риск в группе воздействия?',en:'A study reports RR = 2.0. Baseline risk is 1 in 1,000. What is the approximate exposed-group risk?',et:'Uuring teatab RR = 2,0. Algrisk on 1/1000. Mis on ligikaudne risk kokkupuuterühmas?'},opts:{ru:['2 на 1000','20%','200%','Нельзя ничего сказать'],en:['2 in 1,000','20%','200%','Nothing can be said'],et:['2/1000','20%','200%','Midagi ei saa öelda']},right:0,exp:{ru:'RR 2 означает удвоение риска: 1/1000 → примерно 2/1000. Абсолютное увеличение — около 1 дополнительного случая на 1000.',en:'RR 2 means the risk doubles: 1/1,000 → about 2/1,000. The absolute increase is about 1 additional case per 1,000.',et:'RR 2 tähendab riski kahekordistumist: 1/1000 → umbes 2/1000. Absoluutne kasv on ligikaudu 1 lisajuht 1000 inimese kohta.'}},
    {q:{ru:'P = 0.03. Какое утверждение корректнее?',en:'P = 0.03. Which statement is more accurate?',et:'P = 0,03. Milline väide on täpsem?'},opts:{ru:['Есть 97% шанс, что гипотеза верна','Данные сравнительно плохо совместимы с нулевой моделью при её предпосылках','Эффект обязательно большой','Результат обязательно воспроизведётся'],en:['There is a 97% chance the hypothesis is true','The data are relatively incompatible with the null model under its assumptions','The effect must be large','The result must replicate'],et:['Hüpotees on 97% tõenäosusega tõene','Andmed on nullmudeliga selle eelduste korral suhteliselt halvasti kooskõlas','Mõju peab olema suur','Tulemus peab korduma']},right:1,exp:{ru:'P-value не является вероятностью истинности гипотезы и не измеряет размер эффекта.',en:'A p-value is not the probability that a hypothesis is true and does not measure effect size.',et:'P-väärtus ei ole hüpoteesi tõesuse tõenäosus ega mõõda mõju suurust.'}},
    {q:{ru:'У людей с бессонницей чаще депрессия. Что можно заключить только из этой фразы?',en:'People with insomnia have more depression. What can be concluded from this statement alone?',et:'Unetusega inimestel esineb depressiooni sagedamini. Mida saab ainult sellest lausest järeldada?'},opts:{ru:['Бессонница вызывает депрессию','Депрессия вызывает бессонницу','Есть ассоциация; направление причинности пока не установлено','Обе болезни не связаны'],en:['Insomnia causes depression','Depression causes insomnia','There is an association; causal direction is not established','The conditions are unrelated'],et:['Unetus põhjustab depressiooni','Depressioon põhjustab unetust','On seos; põhjuslik suund pole kindlaks tehtud','Seost pole']},right:2,exp:{ru:'Одной ассоциации недостаточно, чтобы выбрать направление причинности или исключить общие причины.',en:'An association alone cannot establish causal direction or exclude shared causes.',et:'Ainuüksi seos ei määra põhjuslikku suunda ega välista ühiseid põhjuseid.'}},
    {q:{ru:'Что чаще всего уменьшает случайную ошибку, но само по себе не устраняет bias?',en:'What usually reduces random error but does not by itself remove bias?',et:'Mis tavaliselt vähendab juhuslikku viga, kuid ei kõrvalda iseenesest kallutatust?'},opts:{ru:['Большая выборка','Красивый график','Низкий p-value','Известный журнал'],en:['A larger sample','A prettier graph','A low p-value','A famous journal'],et:['Suurem valim','Ilusam graafik','Madal p-väärtus','Tuntud ajakiri']},right:0,exp:{ru:'Больший n обычно повышает точность, но систематическая ошибка может остаться систематической.',en:'A larger n generally improves precision, but systematic error can remain systematic.',et:'Suurem n parandab tavaliselt täpsust, kuid süstemaatiline viga võib alles jääda.'}},
    {q:{ru:'Заголовок: “Риск вырос на 100%”. Что нужно спросить первым?',en:'Headline: “Risk increased by 100%.” What should you ask first?',et:'Pealkiri: „Risk suurenes 100%.“ Mida peaks esmalt küsima?'},opts:{ru:['Какой был исходный абсолютный риск?','Какой цвет графика?','Кто написал пресс-релиз?','Сколько слов в статье?'],en:['What was the baseline absolute risk?','What colour was the graph?','Who wrote the press release?','How many words are in the paper?'],et:['Milline oli absoluutne algrisk?','Mis värvi oli graafik?','Kes kirjutas pressiteate?','Mitu sõna artiklis oli?']},right:0,exp:{ru:'Относительный рост без базового риска может создавать сильно искажённое впечатление о масштабе эффекта.',en:'A relative increase without baseline risk can seriously distort the perceived magnitude of an effect.',et:'Suhteline kasv ilma algriskita võib mõju suurusest väga moonutatud mulje jätta.'}}
  ],
  simulator: [
    {id:'design', title:{ru:'Какой дизайн выберешь?',en:'Which design will you choose?',et:'Millise disaini valid?'},context:{ru:'Ты хочешь проверить, снижает ли новая программа сна дневную сонливость за 8 недель.',en:'You want to test whether a new sleep programme reduces daytime sleepiness over 8 weeks.',et:'Tahad kontrollida, kas uus uneprogramm vähendab 8 nädalaga päevast unisust.'},options:[
      {id:'rct',label:{ru:'Рандомизированное контролируемое исследование',en:'Randomised controlled trial',et:'Randomiseeritud kontrolluuring'},score:3,note:{ru:'Сильный выбор для причинного сравнения, если вмешательство этично и выполнимо.',en:'Strong choice for causal comparison when the intervention is ethical and feasible.',et:'Tugev valik põhjuslikuks võrdluseks, kui sekkumine on eetiline ja teostatav.'}},
      {id:'cross',label:{ru:'Одномоментный опрос после программы',en:'Cross-sectional survey after the programme',et:'Läbilõikeküsitlus pärast programmi'},score:0,note:{ru:'Без исходного сравнения и подходящей контрольной группы причинный вывод будет слабым.',en:'Without baseline comparison and a suitable control group, causal inference is weak.',et:'Ilma algtaseme võrdluse ja sobiva kontrollrühmata on põhjuslik järeldus nõrk.'}},
      {id:'before',label:{ru:'До/после без контрольной группы',en:'Before/after without a control group',et:'Enne/pärast ilma kontrollrühmata'},score:1,note:{ru:'Лучше, чем один замер, но изменения времени и регрессия к среднему могут спутать эффект.',en:'Better than one measurement, but time trends and regression to the mean can mimic an effect.',et:'Parem kui üks mõõtmine, kuid ajatrendid ja regressioon keskmise poole võivad mõju jäljendada.'}}
    ]},
    {id:'sample',title:{ru:'Кого набирать?',en:'Who will you recruit?',et:'Keda värbad?'},context:{ru:'Программа рассчитана на взрослых с хроническими проблемами сна.',en:'The programme is intended for adults with chronic sleep problems.',et:'Programm on mõeldud krooniliste uneprobleemidega täiskasvanutele.'},options:[
      {id:'target',label:{ru:'Набирать по заранее заданным критериям из нескольких клиник и сообщества',en:'Recruit using prespecified criteria from several clinics and the community',et:'Värba eelmääratud kriteeriumidega mitmest kliinikust ja kogukonnast'},score:3,note:{ru:'Разные источники набора и заранее заданные критерии повышают переносимость и прозрачность.',en:'Multiple recruitment sources and prespecified criteria improve transparency and generalisability.',et:'Mitmed värbamisallikad ja eelmääratud kriteeriumid parandavad läbipaistvust ja üldistatavust.'}},
      {id:'friends',label:{ru:'Только знакомых исследовательской команды',en:'Only friends of the research team',et:'Ainult uurimisrühma tuttavad'},score:0,note:{ru:'Удобная выборка может сильно отличаться от целевой популяции.',en:'A convenience sample may differ substantially from the target population.',et:'Mugavusvalim võib sihtpopulatsioonist oluliselt erineda.'}},
      {id:'ads',label:{ru:'Только через рекламу “Хотите лучше спать?”',en:'Only through ads saying “Want to sleep better?”',et:'Ainult reklaamiga „Tahad paremini magada?“'},score:1,note:{ru:'Самоотбор может дать мотивированную и нетипичную выборку.',en:'Self-selection may produce an unusually motivated sample.',et:'Isevalik võib anda ebatavaliselt motiveeritud valimi.'}}
    ]},
    {id:'measure',title:{ru:'Как измерять исход?',en:'How will you measure the outcome?',et:'Kuidas tulemust mõõdad?'},context:{ru:'Главный исход — дневная сонливость.',en:'The main outcome is daytime sleepiness.',et:'Peamine tulemus on päevane unisus.'},options:[
      {id:'validated',label:{ru:'Заранее выбрать валидированную шкалу и основной timepoint',en:'Prespecify a validated scale and primary timepoint',et:'Määra ette valideeritud skaala ja peamine ajapunkt'},score:3,note:{ru:'Предварительно заданный валидированный исход уменьшает свободу анализа.',en:'A prespecified validated outcome reduces analytic flexibility.',et:'Ette määratud valideeritud tulemus vähendab analüütilist paindlikkust.'}},
      {id:'ask',label:{ru:'После исследования спросить: “Стало лучше?”',en:'After the study ask: “Did you feel better?”',et:'Pärast uuringut küsi: „Kas läks paremaks?“'},score:0,note:{ru:'Размытый постфактум исход чувствителен к ожиданиям и исследовательским решениям.',en:'A vague post-hoc outcome is vulnerable to expectations and researcher choices.',et:'Ebamäärane post-hoc tulemus on tundlik ootuste ja uurija valikute suhtes.'}},
      {id:'many',label:{ru:'Измерить 25 шкал и выбрать самую “красивую”',en:'Measure 25 scales and report the nicest-looking one',et:'Mõõda 25 skaalat ja raporteeri kõige „ilusam“'},score:0,note:{ru:'Выбор исхода после просмотра данных повышает риск ложноположительных выводов.',en:'Choosing outcomes after seeing the data inflates false-positive risk.',et:'Tulemuse valimine pärast andmete nägemist suurendab valepositiivse järelduse riski.'}}
    ]},
    {id:'analysis',title:{ru:'Как планировать анализ?',en:'How will you plan the analysis?',et:'Kuidas analüüsi planeerid?'},context:{ru:'До сбора данных нужно определить основной анализ.',en:'The primary analysis must be decided before data collection.',et:'Põhianalüüs tuleb otsustada enne andmete kogumist.'},options:[
      {id:'pre',label:{ru:'Предрегистрация: гипотеза, primary outcome, анализ и исключения',en:'Preregister hypothesis, primary outcome, analysis and exclusions',et:'Eelregistreeri hüpotees, põhitulemus, analüüs ja välistamised'},score:3,note:{ru:'Предрегистрация не гарантирует истину, но делает исследовательские решения прозрачнее.',en:'Preregistration does not guarantee truth, but makes analytic decisions more transparent.',et:'Eelregistreerimine ei taga tõde, kuid muudab analüütilised otsused läbipaistvamaks.'}},
      {id:'iterate',label:{ru:'Пробовать модели, пока p не станет < 0.05',en:'Try models until p becomes < 0.05',et:'Proovi mudeleid, kuni p < 0,05'},score:-1,note:{ru:'Это классический путь к p-hacking и завышенному числу ложных находок.',en:'This is a classic route to p-hacking and excess false positives.',et:'See on klassikaline tee p-hacking’u ja liigsete valepositiivsete tulemusteni.'}},
      {id:'flex',label:{ru:'Решить после сбора данных, но описать все анализы',en:'Decide after data collection but report every analysis',et:'Otsusta pärast andmete kogumist, kuid raporteeri kõik analüüsid'},score:1,note:{ru:'Полная прозрачность помогает, но подтверждающий и исследовательский анализ всё равно лучше различать.',en:'Full transparency helps, but confirmatory and exploratory analyses should still be distinguished.',et:'Täielik läbipaistvus aitab, kuid kinnitavat ja uurivat analüüsi tuleks siiski eristada.'}}
    ]}
  ]
};