window.ETO_DATA = {
  ui: {
    ru: {
      brand: 'Это сложнее', navHome: 'Главная', navLibrary: 'Библиотека', navGames: 'Игры', navGlossary: 'Словарь', navMethod: 'Метод', menu: 'Меню', theme: 'Тема', language: 'Язык',
      heroEyebrow: 'НЕ ТРИВИЯ. КОНТЕКСТ.', heroTitleA: 'Интересный факт —', heroTitleB: 'это только начало.', heroText: 'Короткие интерактивные уроки о мозге, психике, веществах и риске. Сначала — интуиция. Затем — данные, ограничения и источник.', heroPrimary: 'Начать с карточек', heroSecondary: 'Открыть игры',
      cardsEyebrow: 'БЫСТРЫЕ КАРТОЧКИ', cardsTitle: 'Угадай. Проверь. Разбери.', cardsIntro: 'Каждый ответ показывает, что нашли, насколько этому можно доверять и что из этого нельзя заключать.',
      filterAll: 'Все', filterSubstances: 'Вещества', filterBrain: 'Мозг', filterRisk: 'Риск', filterMethod: 'Метод',
      answered: 'Отвечено', of: 'из', reset: 'Сбросить', share: 'Поделиться', retry: 'Ещё раз', copied: 'Ссылка скопирована', shareFail: 'Не удалось поделиться',
      sourceQuality: 'Источник и качество данных', checked: 'Проверено 05.10.2026',
      level3: '●●● высокая', level2: '●●○ средняя', level1: '●○○ контекстная',
      exploreEyebrow: 'ИГРОВОЕ ОБУЧЕНИЕ', exploreTitle: 'Не только читать — пробовать.', exploreText: 'Калькуляторы риска, детектив по искажениям, разбор заголовков и другие упражнения помогают почувствовать статистику руками.', exploreGames: 'Все интерактивы', exploreLibrary: 'Вся библиотека',
      footerA: 'Факты меняются вместе с данными.', footerB: 'Образовательный проект — не медицинская консультация.',
      libraryEyebrow: 'БИБЛИОТЕКА', libraryTitle: 'Все знания в одном месте.', libraryText: 'Ищи по теме или слову. Карточки отсортированы по темам и уровню уверенности.', search: 'Поиск', searchPlaceholder: 'Например: риск, сон, каннабис…', noResults: 'Ничего не найдено. Попробуй другой запрос.', openCard: 'Открыть карточку',
      gamesEyebrow: 'ИНТЕРАКТИВЫ', gamesTitle: 'Понять через действие.', gamesText: 'Это учебные симуляторы, а не медицинские калькуляторы. Числа здесь помогают понять принципы.',
      riskLabTitle: 'Лаборатория абсолютного риска', riskLabText: 'Посмотри, как один и тот же относительный риск выглядит при разных исходных вероятностях.', baseline: 'Исходный риск, %', rr: 'Относительный риск (RR)', result: 'Результат', newRisk: 'Новый риск', absoluteChange: 'Абсолютное изменение', per1000: 'На 1000 человек',
      oddsTitle: 'OR → вероятность: почему нужен базовый риск', oddsText: 'Переведи odds ratio в новую вероятность при заданной исходной вероятности. Это математическая демонстрация, не оценка личного риска.', baselineProbability: 'Исходная вероятность, %', oddsRatio: 'Odds ratio', estimatedProbability: 'Расчётная вероятность',
      biasTitle: 'Детектив по искажениям', biasText: 'Прочитай мини-сценарий и выбери наиболее вероятную проблему дизайна.', next: 'Следующий', correct: 'Верно', incorrect: 'Не совсем', score: 'Счёт',
      headlineTitle: 'Разбери заголовок', headlineText: 'Отметь, чего не хватает, чтобы интерпретировать медицинский заголовок.', checkAnswer: 'Проверить',
      glossaryEyebrow: 'СЛОВАРЬ', glossaryTitle: 'Термины без тумана.', glossaryText: 'Короткие определения статистики, эпидемиологии и доказательной медицины.', glossaryPlaceholder: 'Найти термин…',
      methodEyebrow: 'МЕТОД', methodTitle: 'Как мы превращаем исследование в карточку.', methodText: 'Наша задача — не сделать вывод громче, а сделать его точнее.',
      method1: '1. Формулируем конкретный вопрос', method1p: 'Кто изучался? Какое воздействие? Какой исход? С чем сравнивали?',
      method2: '2. Определяем дизайн', method2p: 'RCT, когортное, case-control, мета-анализ или модель отвечают на разные вопросы и несут разные ограничения.',
      method3: '3. Разделяем относительное и абсолютное', method3p: 'RR, OR и hazard ratio не являются вероятностями. По возможности показываем исходный риск и абсолютное изменение.',
      method4: '4. Ищем границы вывода', method4p: 'Confounding, selection bias, измерения, переносимость и неопределённость — часть результата, а не сноска.',
      method5: '5. Даём первичный источник', method5p: 'Предпочитаем оригинальное исследование, систематический обзор или клиническое руководство вместо пересказа.',
      method6: '6. Датируем проверку', method6p: 'Карточка — версия знания на конкретную дату. При изменении данных формулировка должна меняться.'
    },
    en: {
      brand: 'It’s more complicated', navHome: 'Home', navLibrary: 'Library', navGames: 'Games', navGlossary: 'Glossary', navMethod: 'Method', menu: 'Menu', theme: 'Theme', language: 'Language',
      heroEyebrow: 'NOT TRIVIA. CONTEXT.', heroTitleA: 'An interesting fact is', heroTitleB: 'only the beginning.', heroText: 'Short interactive lessons about the brain, mental health, substances and risk. Start with intuition, then inspect the data, limitations and source.', heroPrimary: 'Start with cards', heroSecondary: 'Open games',
      cardsEyebrow: 'QUICK CARDS', cardsTitle: 'Guess. Check. Unpack.', cardsIntro: 'Every answer shows what was found, how confident we can be, and what the result does not establish.',
      filterAll: 'All', filterSubstances: 'Substances', filterBrain: 'Brain', filterRisk: 'Risk', filterMethod: 'Method',
      answered: 'Answered', of: 'of', reset: 'Reset', share: 'Share', retry: 'Try again', copied: 'Link copied', shareFail: 'Could not share',
      sourceQuality: 'Source and evidence quality', checked: 'Checked 05 Oct 2026',
      level3: '●●● high', level2: '●●○ moderate', level1: '●○○ contextual',
      exploreEyebrow: 'LEARN BY DOING', exploreTitle: 'Don’t just read — interact.', exploreText: 'Risk calculators, bias detective, headline deconstruction and other exercises make statistical ideas tangible.', exploreGames: 'All interactives', exploreLibrary: 'Full library',
      footerA: 'Facts change as evidence changes.', footerB: 'Educational project — not medical advice.',
      libraryEyebrow: 'LIBRARY', libraryTitle: 'All knowledge in one place.', libraryText: 'Search by topic or word. Cards are organised by subject and confidence level.', search: 'Search', searchPlaceholder: 'Try: risk, sleep, cannabis…', noResults: 'Nothing found. Try another query.', openCard: 'Open card',
      gamesEyebrow: 'INTERACTIVES', gamesTitle: 'Understand by doing.', gamesText: 'These are learning simulations, not medical calculators. The numbers are here to teach principles.',
      riskLabTitle: 'Absolute risk lab', riskLabText: 'See how the same relative risk looks very different at different baseline risks.', baseline: 'Baseline risk, %', rr: 'Relative risk (RR)', result: 'Result', newRisk: 'New risk', absoluteChange: 'Absolute change', per1000: 'Per 1,000 people',
      oddsTitle: 'OR → probability: why baseline risk matters', oddsText: 'Convert an odds ratio to a new probability for a chosen baseline probability. This is a mathematical demonstration, not a personal risk estimate.', baselineProbability: 'Baseline probability, %', oddsRatio: 'Odds ratio', estimatedProbability: 'Estimated probability',
      biasTitle: 'Bias detective', biasText: 'Read the scenario and choose the most likely design problem.', next: 'Next', correct: 'Correct', incorrect: 'Not quite', score: 'Score',
      headlineTitle: 'Deconstruct a headline', headlineText: 'Select what information is missing before a medical headline can be interpreted.', checkAnswer: 'Check',
      glossaryEyebrow: 'GLOSSARY', glossaryTitle: 'Terms without the fog.', glossaryText: 'Short definitions from statistics, epidemiology and evidence-based medicine.', glossaryPlaceholder: 'Find a term…',
      methodEyebrow: 'METHOD', methodTitle: 'How we turn a study into a card.', methodText: 'The goal is not to make a conclusion louder, but to make it more precise.',
      method1: '1. Define the question', method1p: 'Who was studied? What exposure? What outcome? What comparison?',
      method2: '2. Identify the design', method2p: 'RCTs, cohorts, case-control studies, meta-analyses and models answer different questions and carry different limitations.',
      method3: '3. Separate relative from absolute', method3p: 'RR, OR and hazard ratios are not probabilities. When possible, we show baseline risk and absolute change.',
      method4: '4. Find the boundaries', method4p: 'Confounding, selection bias, measurement, generalisability and uncertainty are part of the result, not a footnote.',
      method5: '5. Link the primary source', method5p: 'We prefer original studies, systematic reviews or clinical guidelines over media summaries.',
      method6: '6. Date the review', method6p: 'A card is a version of knowledge at a point in time. If the evidence changes, the wording should change.'
    },
    et: {
      brand: 'See on keerulisem', navHome: 'Avaleht', navLibrary: 'Teek', navGames: 'Mängud', navGlossary: 'Sõnastik', navMethod: 'Meetod', menu: 'Menüü', theme: 'Teema', language: 'Keel',
      heroEyebrow: 'MITTE TRIVIA. KONTEKST.', heroTitleA: 'Huvitav fakt on', heroTitleB: 'alles algus.', heroText: 'Lühikesed interaktiivsed õppetunnid ajust, vaimsest tervisest, ainetest ja riskist. Alusta intuitsioonist, seejärel vaata andmeid, piiranguid ja allikat.', heroPrimary: 'Alusta kaartidega', heroSecondary: 'Ava mängud',
      cardsEyebrow: 'KIIRKAARDID', cardsTitle: 'Arva. Kontrolli. Mõtesta.', cardsIntro: 'Iga vastus näitab, mida leiti, kui kindel järeldus on ja mida tulemus ei tõesta.',
      filterAll: 'Kõik', filterSubstances: 'Ained', filterBrain: 'Aju', filterRisk: 'Risk', filterMethod: 'Meetod',
      answered: 'Vastatud', of: '/', reset: 'Lähtesta', share: 'Jaga', retry: 'Proovi uuesti', copied: 'Link kopeeritud', shareFail: 'Jagamine ebaõnnestus',
      sourceQuality: 'Allikas ja tõenduse kvaliteet', checked: 'Kontrollitud 05.10.2026',
      level3: '●●● kõrge', level2: '●●○ keskmine', level1: '●○○ kontekstipõhine',
      exploreEyebrow: 'ÕPI TEGUTSEDES', exploreTitle: 'Ära ainult loe — proovi.', exploreText: 'Riskikalkulaatorid, kallutatuse detektiiv, pealkirjade analüüs ja teised harjutused teevad statistika käegakatsutavaks.', exploreGames: 'Kõik interaktiivid', exploreLibrary: 'Kogu teek',
      footerA: 'Faktid muutuvad koos tõendusmaterjaliga.', footerB: 'Hariduslik projekt — mitte meditsiiniline nõuanne.',
      libraryEyebrow: 'TEEK', libraryTitle: 'Kõik teadmised ühes kohas.', libraryText: 'Otsi teema või sõna järgi. Kaardid on rühmitatud valdkonna ja kindluse järgi.', search: 'Otsing', searchPlaceholder: 'Näiteks: risk, uni, kanep…', noResults: 'Midagi ei leitud. Proovi teist otsingut.', openCard: 'Ava kaart',
      gamesEyebrow: 'INTERAKTIIVID', gamesTitle: 'Mõista läbi tegevuse.', gamesText: 'Need on õppesimulatsioonid, mitte meditsiinilised kalkulaatorid. Numbrid aitavad põhimõtteid mõista.',
      riskLabTitle: 'Absoluutse riski labor', riskLabText: 'Vaata, kuidas sama suhteline risk näeb välja väga erinev erineva algtaseme korral.', baseline: 'Algrisk, %', rr: 'Suhteline risk (RR)', result: 'Tulemus', newRisk: 'Uus risk', absoluteChange: 'Absoluutne muutus', per1000: '1000 inimese kohta',
      oddsTitle: 'OR → tõenäosus: miks algrisk loeb', oddsText: 'Teisenda odds ratio uueks tõenäosuseks valitud algtõenäosuse korral. See on matemaatiline näide, mitte isiklik riskihinnang.', baselineProbability: 'Algtõenäosus, %', oddsRatio: 'Odds ratio', estimatedProbability: 'Arvutatud tõenäosus',
      biasTitle: 'Kallutatuse detektiiv', biasText: 'Loe olukorda ja vali kõige tõenäolisem uuringudisaini probleem.', next: 'Järgmine', correct: 'Õige', incorrect: 'Mitte päris', score: 'Skoor',
      headlineTitle: 'Lahka pealkirja', headlineText: 'Märgi, milline info on puudu, et meditsiinipealkirja saaks mõistlikult tõlgendada.', checkAnswer: 'Kontrolli',
      glossaryEyebrow: 'SÕNASTIK', glossaryTitle: 'Terminid ilma uduta.', glossaryText: 'Lühikesed seletused statistikast, epidemioloogiast ja tõenduspõhisest meditsiinist.', glossaryPlaceholder: 'Otsi terminit…',
      methodEyebrow: 'MEETOD', methodTitle: 'Kuidas uuringust saab kaart.', methodText: 'Eesmärk ei ole teha järeldust valjemaks, vaid täpsemaks.',
      method1: '1. Sõnastame küsimuse', method1p: 'Keda uuriti? Mis oli kokkupuude? Mis oli tulemus? Millega võrreldi?',
      method2: '2. Tuvastame uuringudisaini', method2p: 'RCT, kohort, juht-kontrolluuring, meta-analüüs ja mudel vastavad erinevatele küsimustele ning neil on erinevad piirangud.',
      method3: '3. Eristame suhtelist ja absoluutset', method3p: 'RR, OR ja hazard ratio ei ole tõenäosused. Võimalusel näitame algriski ja absoluutset muutust.',
      method4: '4. Otsime järelduse piire', method4p: 'Segavad tegurid, valikukallutatus, mõõtmine, üldistatavus ja ebakindlus on osa tulemusest, mitte joonealune märkus.',
      method5: '5. Viitame algallikale', method5p: 'Eelistame originaaluuringut, süstemaatilist ülevaadet või kliinilist juhendit meediakokkuvõttele.',
      method6: '6. Lisame kontrollimise kuupäeva', method6p: 'Kaart on teadmise versioon kindlal ajahetkel. Kui tõendus muutub, peab muutuma ka sõnastus.'
    }
  },
  cards: [
    {
      id:'alcohol-cannabis-harm', category:'substances risk', level:1, source:'https://doi.org/10.1016/S0140-6736(10)61462-6', sourceName:'Nutt et al., Lancet, 2010',
      ru:{tag:'Вещества', kicker:'Сравнение вреда', q:'Можно ли сказать, что алкоголь «объективно опаснее» каннабиса?', options:['Да, всегда и для любого человека','Нет, это зависит от того, что именно считать вредом'], right:1, answer:'В известной британской MCDA-модели алкоголь получил более высокий суммарный балл вреда, чем каннабис. Но модель объединяет разные виды вреда с экспертно заданными весами.', caveat:'Не утверждаем, что такой рейтинг является универсальной шкалой токсичности для каждого человека, дозы и ситуации.', design:'MCDA, экспертная многокритериальная модель.'},
      en:{tag:'Substances', kicker:'Comparing harm', q:'Can we say alcohol is “objectively more dangerous” than cannabis?', options:['Yes, always and for everyone','No, it depends on what kind of harm is being measured'], right:1, answer:'In a well-known UK MCDA model, alcohol received a higher total harm score than cannabis. But the model combines different individual and societal harms using expert-assigned weights.', caveat:'This does not establish a universal toxicity ranking for every person, dose or situation.', design:'MCDA, expert multicriteria model.'},
      et:{tag:'Ained', kicker:'Kahju võrdlemine', q:'Kas saab öelda, et alkohol on kanepist „objektiivselt ohtlikum“?', options:['Jah, alati ja kõigi jaoks','Ei, see sõltub sellest, millist kahju mõõdetakse'], right:1, answer:'Tuntud Ühendkuningriigi MCDA-mudelis sai alkohol kanepist kõrgema kogukahju skoori. Mudel ühendab aga eri tüüpi individuaalse ja ühiskondliku kahju ekspertide antud kaaludega.', caveat:'See ei ole universaalne toksilisuse pingerida iga inimese, annuse või olukorra jaoks.', design:'MCDA, ekspertide mitmekriteeriumiline mudel.'}
    },
    {
      id:'odds-ratio-not-percent', category:'risk method', level:3, source:'https://training.cochrane.org/handbook/current/chapter-06', sourceName:'Cochrane Handbook, Chapter 6',
      ru:{tag:'Риск', kicker:'Относительные меры', q:'Если отношение шансов равно 4, означает ли это, что риск равен 40%?', options:['Да','Нет'], right:1, answer:'Нет. Odds ratio — относительная мера, а не абсолютная вероятность. Без базового риска число 4 не говорит, сколько людей реально столкнутся с исходом.', caveat:'OR и risk ratio не взаимозаменяемы; при частых исходах они могут заметно различаться.', design:'Методологический принцип интерпретации эффектов.'},
      en:{tag:'Risk', kicker:'Relative measures', q:'If the odds ratio is 4, does that mean the risk is 40%?', options:['Yes','No'], right:1, answer:'No. An odds ratio is a relative measure, not an absolute probability. Without baseline risk, the number 4 does not tell you how many people will experience the outcome.', caveat:'OR and risk ratio are not interchangeable and can differ substantially for common outcomes.', design:'Methodological principle for interpreting effects.'},
      et:{tag:'Risk', kicker:'Suhtelised mõõdikud', q:'Kui odds ratio on 4, kas see tähendab, et risk on 40%?', options:['Jah','Ei'], right:1, answer:'Ei. Odds ratio on suhteline mõõdik, mitte absoluutne tõenäosus. Ilma algriskita ei ütle arv 4, kui paljudel inimestel tulemus tekib.', caveat:'OR ja riskisuhe ei ole samad ning sagedaste tulemuste korral võivad need märgatavalt erineda.', design:'Mõju suuruse tõlgendamise metodoloogiline põhimõte.'}
    },
    {
      id:'cannabis-psychosis', category:'substances risk', level:2, source:'https://doi.org/10.1016/S2215-0366(19)30048-3', sourceName:'Di Forti et al., Lancet Psychiatry, 2019',
      ru:{tag:'Вещества', kicker:'Ассоциация ≠ судьба', q:'Ежедневное употребление высокопотентного каннабиса связано с более высокими шансами первого эпизода психоза?', options:['Да, такая связь наблюдалась','Нет, такой связи не находили'], right:0, answer:'Да. В исследовании EU-GEI частое употребление высокопотентного каннабиса было связано с более высокими odds первого эпизода психоза.', caveat:'Наблюдательное исследование не задаёт личную вероятность и не исключает все смешивающие факторы.', design:'Многоцентровое case-control исследование.'},
      en:{tag:'Substances', kicker:'Association ≠ destiny', q:'Is daily use of high-potency cannabis associated with higher odds of a first psychotic episode?', options:['Yes, this association has been observed','No, studies have not found such an association'], right:0, answer:'Yes. In EU-GEI, frequent use of high-potency cannabis was associated with higher odds of first-episode psychosis.', caveat:'An observational study does not define an individual probability and cannot eliminate every source of confounding.', design:'Multicentre case-control study.'},
      et:{tag:'Ained', kicker:'Seos ≠ saatus', q:'Kas kõrge THC-sisaldusega kanepi igapäevane tarvitamine on seotud suurema esimese psühhoosiepisoodi šansiga?', options:['Jah, sellist seost on täheldatud','Ei, uuringud pole sellist seost leidnud'], right:0, answer:'Jah. EU-GEI uuringus seostus sage kõrge THC-sisaldusega kanepi tarvitamine suurema esimese psühhoosiepisoodi šansiga.', caveat:'Vaatlusuuring ei anna inimese isiklikku tõenäosust ega välista kõiki segavaid tegureid.', design:'Mitmekeskuseline juht-kontrolluuring.'}
    },
    {
      id:'alcohol-withdrawal', category:'substances risk', level:3, source:'https://www.asam.org/quality-care/clinical-guidelines/alcohol-withdrawal-management', sourceName:'ASAM Clinical Practice Guideline',
      ru:{tag:'Вещества', kicker:'Синдром отмены', q:'Отмена алкоголя после тяжёлого длительного употребления может быть опасной для жизни?', options:['Да','Нет, это просто неприятно'], right:0, answer:'Да. Тяжёлая алкогольная абстиненция может включать судороги и алкогольный делирий и требовать интенсивного медицинского наблюдения.', caveat:'Карточка не предназначена для самостоятельного планирования отмены. При риске тяжёлой абстиненции нужна медицинская оценка.', design:'Клиническое руководство.'},
      en:{tag:'Substances', kicker:'Withdrawal', q:'Can alcohol withdrawal after heavy long-term use be life-threatening?', options:['Yes','No, it is only unpleasant'], right:0, answer:'Yes. Severe alcohol withdrawal can involve seizures and delirium and may require intensive medical monitoring.', caveat:'This card is not a guide for self-managed withdrawal. People at risk of severe withdrawal need medical assessment.', design:'Clinical practice guideline.'},
      et:{tag:'Ained', kicker:'Võõrutus', q:'Kas alkoholi võõrutus pärast pikaajalist rasket tarvitamist võib olla eluohtlik?', options:['Jah','Ei, see on lihtsalt ebameeldiv'], right:0, answer:'Jah. Raske alkoholivõõrutus võib hõlmata krampe ja deliiriumi ning vajada intensiivset meditsiinilist jälgimist.', caveat:'See kaart ei ole iseseisva võõrutuse juhend. Raske võõrutuse risk vajab meditsiinilist hindamist.', design:'Kliiniline ravijuhend.'}
    },
    {
      id:'association-causation', category:'method', level:3, source:'https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/', sourceName:'Hernán & Robins, Causal Inference',
      ru:{tag:'Метод', kicker:'Причинный вывод', q:'Если две вещи связаны статистически, доказано ли, что одна вызывает другую?', options:['Да','Нет'], right:1, answer:'Нет. Ассоциация может отражать причинный эффект, обратную причинность, confounding, ошибки измерения или их комбинацию.', caveat:'Наблюдательные исследования не бесполезны, но причинная интерпретация требует дополнительных предпосылок и анализа.', design:'Методология причинного вывода.'},
      en:{tag:'Method', kicker:'Causal inference', q:'If two things are statistically associated, is it proven that one causes the other?', options:['Yes','No'], right:1, answer:'No. An association can reflect causation, reverse causation, confounding, measurement error, or a combination of these.', caveat:'Observational studies are not useless, but causal interpretation requires additional assumptions and analysis.', design:'Causal inference methodology.'},
      et:{tag:'Meetod', kicker:'Põhjuslik järeldus', q:'Kui kaks asja on statistiliselt seotud, kas see tõestab, et üks põhjustab teist?', options:['Jah','Ei'], right:1, answer:'Ei. Seos võib peegeldada põhjuslikku mõju, vastupidist põhjuslikkust, segavaid tegureid, mõõtmisvigu või nende kombinatsiooni.', caveat:'Vaatlusuuringud pole kasutud, kuid põhjuslik tõlgendus vajab lisaeeldusi ja analüüsi.', design:'Põhjusliku järeldamise metodoloogia.'}
    },
    {
      id:'denominator', category:'method risk', level:3, source:'https://www.cdc.gov/field-epi-manual/php/chapters/collecting-data.html', sourceName:'CDC Field Epidemiology Manual',
      ru:{tag:'Метод', kicker:'Одна цифра — не ответ', q:'Можно ли сравнить «30% зависимости» и «60% зависимости», если знаменатели разные?', options:['Да, большее число всегда означает больший риск','Нет, сначала нужен сопоставимый знаменатель'], right:1, answer:'Нет. «Среди всех когда-либо пробовавших» и «среди регулярных пользователей» — разные популяции.', caveat:'Даже одинаковый знаменатель не решает всё: определения исхода, возраст и период наблюдения тоже должны быть сопоставимы.', design:'Принцип описательной эпидемиологии.'},
      en:{tag:'Method', kicker:'One number is not an answer', q:'Can “30% dependence” and “60% dependence” be compared when the denominators differ?', options:['Yes, the larger number always means higher risk','No, the denominator must first be comparable'], right:1, answer:'No. “Among everyone who ever tried” and “among regular users” describe different populations.', caveat:'Even matching denominators is not enough if outcome definitions, ages or follow-up periods differ.', design:'Descriptive epidemiology principle.'},
      et:{tag:'Meetod', kicker:'Üks number pole vastus', q:'Kas „30% sõltuvust“ ja „60% sõltuvust“ saab võrrelda, kui nimetajad on erinevad?', options:['Jah, suurem number tähendab alati suuremat riski','Ei, esmalt peab nimetaja olema võrreldav'], right:1, answer:'Ei. „Kõigi kunagi proovinutest“ ja „regulaarsetest tarvitajatest“ kirjeldavad erinevaid populatsioone.', caveat:'Ka sama nimetaja ei lahenda kõike: tulemuse definitsioon, vanus ja jälgimisperiood peavad samuti olema võrreldavad.', design:'Kirjeldava epidemioloogia põhimõte.'}
    },
    {
      id:'alcohol-cancer', category:'substances risk', level:3, source:'https://www.who.int/europe/news-room/fact-sheets/item/alcohol-and-cancer', sourceName:'WHO Europe: Alcohol and cancer',
      ru:{tag:'Вещества', kicker:'Канцерогенность', q:'Алкоголь считается установленной причиной нескольких видов рака?', options:['Да','Нет, связь есть только с болезнями печени'], right:0, answer:'Да. WHO/IARC указывают причинную связь алкоголя по меньшей мере с семью локализациями рака.', caveat:'Это изменение вероятности, а не детерминированный исход для каждого употребляющего алкоголь.', design:'Оценка международного агентства и совокупность эпидемиологических данных.'},
      en:{tag:'Substances', kicker:'Carcinogenicity', q:'Is alcohol considered an established cause of several cancers?', options:['Yes','No, it is only linked to liver disease'], right:0, answer:'Yes. WHO/IARC describe alcohol as causally related to at least seven cancer sites.', caveat:'This is a change in probability, not a deterministic outcome for every person who drinks alcohol.', design:'International agency assessment and epidemiological evidence.'},
      et:{tag:'Ained', kicker:'Kantserogeensus', q:'Kas alkoholi peetakse mitme vähiliigi tõestatud põhjuseks?', options:['Jah','Ei, seos on ainult maksahaigustega'], right:0, answer:'Jah. WHO/IARC kirjeldab alkoholi põhjusliku tegurina vähemalt seitsme vähiliigi puhul.', caveat:'See tähendab tõenäosuse muutust, mitte vältimatut tulemust iga alkoholi tarvitava inimese jaoks.', design:'Rahvusvahelise agentuuri hinnang ja epidemioloogiliste andmete kogum.'}
    },
    {
      id:'nrt-smoking', category:'substances risk', level:3, source:'https://www.cochrane.org/evidence/CD000146_can-nicotine-replacement-therapy-nrt-help-people-quit-smoking', sourceName:'Cochrane Review: NRT',
      ru:{tag:'Вещества', kicker:'Никотин ≠ дым', q:'Может ли никотин-заместительная терапия помогать бросить курить, не воспроизводя токсичность горения сигарет?', options:['Да','Нет, никотин делает её эквивалентной сигаретам'], right:0, answer:'Да. Систематические обзоры показывают, что NRT повышает вероятность успешного отказа от курения и доставляет никотин без продуктов горения табака.', caveat:'NRT не лишена побочных эффектов и подходит не каждому в любой ситуации.', design:'Систематический обзор рандомизированных исследований.'},
      en:{tag:'Substances', kicker:'Nicotine ≠ smoke', q:'Can nicotine replacement therapy help people quit smoking without reproducing the toxicity of cigarette combustion?', options:['Yes','No, nicotine makes it equivalent to cigarettes'], right:0, answer:'Yes. Systematic reviews show that NRT increases quit rates and delivers nicotine without the products of tobacco combustion.', caveat:'NRT is not free of side effects and is not automatically suitable for everyone in every situation.', design:'Systematic review of randomised trials.'},
      et:{tag:'Ained', kicker:'Nikotiin ≠ suits', q:'Kas nikotiinasendusravi võib aidata suitsetamisest loobuda ilma sigareti põlemise toksilisust kordamata?', options:['Jah','Ei, nikotiin teeb selle sigaretiga samaväärseks'], right:0, answer:'Jah. Süstemaatilised ülevaated näitavad, et NRT suurendab suitsetamisest loobumise tõenäosust ja annab nikotiini ilma tubaka põlemisproduktideta.', caveat:'NRT-l võivad olla kõrvaltoimed ja see ei sobi automaatselt kõigile igas olukorras.', design:'Randomiseeritud uuringute süstemaatiline ülevaade.'}
    },
    {
      id:'cannabis-driving', category:'substances risk', level:2, source:'https://doi.org/10.1111/add.13347', sourceName:'Rogeberg & Elvik, Addiction, 2016',
      ru:{tag:'Вещества', kicker:'Вождение', q:'Острое опьянение каннабисом связано с повышением риска ДТП?', options:['Да, в среднем риск выше','Нет, исследования не находят повышения'], right:0, answer:'Да. Мета-анализ наблюдательных исследований нашёл статистически значимое повышение риска ДТП низкой–умеренной величины.', caveat:'Средний OR не равен личной вероятности аварии и зависит от дозы, времени после употребления и сочетания с алкоголем.', design:'Мета-анализ наблюдательных исследований.'},
      en:{tag:'Substances', kicker:'Driving', q:'Is acute cannabis intoxication associated with a higher risk of motor vehicle crashes?', options:['Yes, average risk is higher','No, studies find no increase'], right:0, answer:'Yes. A meta-analysis of observational studies found a statistically significant low-to-moderate increase in crash risk.', caveat:'The average OR is not a personal crash probability and can vary with dose, time since use, and alcohol co-use.', design:'Meta-analysis of observational studies.'},
      et:{tag:'Ained', kicker:'Autojuhtimine', q:'Kas äge kanepijoove on seotud suurema liiklusõnnetuse riskiga?', options:['Jah, keskmine risk on suurem','Ei, uuringud ei leia tõusu'], right:0, answer:'Jah. Vaatlusuuringute meta-analüüs leidis statistiliselt olulise väikese kuni mõõduka liiklusõnnetuse riski tõusu.', caveat:'Keskmine OR ei ole inimese isiklik õnnetuse tõenäosus ning sõltub annusest, tarvitamisest möödunud ajast ja alkoholist.', design:'Vaatlusuuringute meta-analüüs.'}
    },
    {
      id:'sleep-debt', category:'brain risk', level:2, source:'https://pubmed.ncbi.nlm.nih.gov/12683469/', sourceName:'Van Dongen et al., Sleep, 2003',
      ru:{tag:'Мозг', kicker:'Сон и внимание', q:'Можно ли несколько ночей спать по 4–6 часов и полностью «привыкнуть» без накопления когнитивных потерь?', options:['Да, субъективное привыкание означает отсутствие дефицита','Нет, объективные дефициты могут накапливаться'], right:1, answer:'Нет. В лабораторном эксперименте 14 дней ограничения сна сопровождались накоплением дозозависимых нарушений когнитивной производительности.', caveat:'Результаты небольшой лабораторной выборки нельзя автоматически переносить на любой возраст и состояние здоровья.', design:'Рандомизированный лабораторный эксперимент.'},
      en:{tag:'Brain', kicker:'Sleep and attention', q:'Can you sleep 4–6 hours for several nights and fully “adapt” without accumulating cognitive deficits?', options:['Yes, feeling adapted means there is no deficit','No, objective deficits can accumulate'], right:1, answer:'No. In a laboratory experiment, 14 days of restricted sleep produced accumulating dose-dependent cognitive performance deficits.', caveat:'A small laboratory sample cannot automatically be generalised to every age group or health condition.', design:'Randomised laboratory experiment.'},
      et:{tag:'Aju', kicker:'Uni ja tähelepanu', q:'Kas mitmel ööl 4–6 tundi magades saab täielikult „harjuda“ ilma kognitiivsete puudujääkide kuhjumiseta?', options:['Jah, harjumise tunne tähendab puudujäägi puudumist','Ei, objektiivsed puudujäägid võivad kuhjuda'], right:1, answer:'Ei. Laborikatses põhjustas 14 päeva piiratud und kuhjuvaid ja annusest sõltuvaid kognitiivse soorituse puudujääke.', caveat:'Väikest laboriproovi ei saa automaatselt üldistada igale vanusele või terviseseisundile.', design:'Randomiseeritud laborikatse.'}
    },
    {
      id:'memory-wording', category:'brain method', level:2, source:'https://doi.org/10.1016/S0022-5371(74)80011-3', sourceName:'Loftus & Palmer, 1974',
      ru:{tag:'Мозг', kicker:'Память реконструируется', q:'Может ли формулировка вопроса после события изменить последующее воспоминание?', options:['Да','Нет, память хранит неизменяемую запись'], right:0, answer:'Да. В классических экспериментах изменение формулировки вопроса влияло на оценку скорости и последующие сообщения о деталях события.', caveat:'Это не означает, что любые воспоминания легко переписать или что наличие ошибки делает всю память ненадёжной.', design:'Два лабораторных эксперимента.'},
      en:{tag:'Brain', kicker:'Memory is reconstructive', q:'Can the wording of a question after an event change later memory reports?', options:['Yes','No, memory stores an unchangeable recording'], right:0, answer:'Yes. In classic experiments, changing the wording of a question influenced speed estimates and later reports about event details.', caveat:'This does not mean every memory is easy to rewrite or that one error makes all memory unreliable.', design:'Two laboratory experiments.'},
      et:{tag:'Aju', kicker:'Mälu on rekonstruktiivne', q:'Kas sündmuse järel esitatud küsimuse sõnastus võib muuta hilisemat mälestust?', options:['Jah','Ei, mälu talletab muutumatu salvestise'], right:0, answer:'Jah. Klassikalistes katsetes mõjutas küsimuse sõnastus kiiruse hinnangut ja hilisemaid teateid sündmuse detailide kohta.', caveat:'See ei tähenda, et kõiki mälestusi saab kergesti ümber kirjutada või et üks viga muudab kogu mälu ebausaldusväärseks.', design:'Kaks laborikatset.'}
    },
    {
      id:'pvalue-truth', category:'method risk', level:3, source:'https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf', sourceName:'American Statistical Association, 2016',
      ru:{tag:'Метод', kicker:'p-value', q:'Если p = 0.03, означает ли это 97% вероятность, что гипотеза исследователей верна?', options:['Да','Нет'], right:1, answer:'Нет. P-value не является вероятностью истинности гипотезы. Он характеризует совместимость данных с заданной статистической моделью при её предпосылках.', caveat:'Проблема не в самом p-value, а в интерпретации его как вероятности истины или единственного критерия вывода.', design:'Методологическое заявление ASA.'},
      en:{tag:'Method', kicker:'p-value', q:'If p = 0.03, does that mean there is a 97% probability the researchers’ hypothesis is true?', options:['Yes','No'], right:1, answer:'No. A p-value is not the probability that a hypothesis is true. It describes how compatible the data are with a specified statistical model under its assumptions.', caveat:'The problem is not the existence of p-values, but treating them as probabilities of truth or the sole criterion for inference.', design:'ASA methodological statement.'},
      et:{tag:'Meetod', kicker:'p-väärtus', q:'Kui p = 0,03, kas see tähendab 97% tõenäosust, et teadlaste hüpotees on tõene?', options:['Jah','Ei'], right:1, answer:'Ei. P-väärtus ei ole hüpoteesi tõesuse tõenäosus. See kirjeldab andmete kooskõla etteantud statistilise mudeliga selle eelduste korral.', caveat:'Probleem pole p-väärtuse olemasolus, vaid selle tõlgendamises tõe tõenäosuse või ainsa järelduskriteeriumina.', design:'ASA metodoloogiline seisukoht.'}
    },
    {
      id:'pvalue-effect-size', category:'method risk', level:3, source:'https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf', sourceName:'ASA Statement on P-Values',
      ru:{tag:'Метод', kicker:'Значимость ≠ важность', q:'Статистически значимый результат обязательно означает большой и практически важный эффект?', options:['Да','Нет'], right:1, answer:'Нет. Статистическая значимость не измеряет размер эффекта или его практическую важность.', caveat:'Малый эффект не всегда неважен: на уровне большой популяции небольшие индивидуальные эффекты могут иметь значение.', design:'Статистический принцип интерпретации.'},
      en:{tag:'Method', kicker:'Significance ≠ importance', q:'Does a statistically significant result necessarily imply a large and practically important effect?', options:['Yes','No'], right:1, answer:'No. Statistical significance does not measure effect size or practical importance.', caveat:'A small effect is not always unimportant: across a large population, small individual effects can matter.', design:'Statistical interpretation principle.'},
      et:{tag:'Meetod', kicker:'Olulisus ≠ tähtsus', q:'Kas statistiliselt oluline tulemus tähendab tingimata suurt ja praktiliselt tähtsat mõju?', options:['Jah','Ei'], right:1, answer:'Ei. Statistiline olulisus ei mõõda mõju suurust ega praktilist tähtsust.', caveat:'Väike mõju ei ole alati tähtsusetu: suure populatsiooni tasandil võivad väikesed individuaalsed mõjud olla olulised.', design:'Statistilise tõlgendamise põhimõte.'}
    },
    {
      id:'rct-generalizability', category:'method', level:3, source:'https://pubmed.ncbi.nlm.nih.gov/15639683/', sourceName:'Rothwell, Lancet, 2005',
      ru:{tag:'Метод', kicker:'Внешняя валидность', q:'Если исследование рандомизированное, его результат автоматически применим ко всем людям?', options:['Да','Нет'], right:1, answer:'Нет. Рандомизация помогает внутренней валидности сравнения внутри изученной выборки. Переносимость на другие группы — отдельный вопрос.', caveat:'Внутренняя и внешняя валидность отвечают на разные вопросы; одна не гарантирует другую.', design:'Методологический обзор.'},
      en:{tag:'Method', kicker:'External validity', q:'If a study is randomised, does its result automatically apply to everyone?', options:['Yes','No'], right:1, answer:'No. Randomisation supports internal validity within the studied sample. Generalisability to other groups is a separate question.', caveat:'Internal and external validity answer different questions; one does not guarantee the other.', design:'Methodological review.'},
      et:{tag:'Meetod', kicker:'Väline valiidsus', q:'Kui uuring on randomiseeritud, kas selle tulemus kehtib automaatselt kõigi inimeste kohta?', options:['Jah','Ei'], right:1, answer:'Ei. Randomiseerimine toetab sisemist valiidsust uuritud valimis. Üldistatavus teistele rühmadele on eraldi küsimus.', caveat:'Sisemine ja väline valiidsus vastavad eri küsimustele; üks ei taga teist.', design:'Metodoloogiline ülevaade.'}
    },
    {
      id:'large-sample-bias', category:'method', level:3, source:'https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/', sourceName:'Hernán & Robins, Causal Inference',
      ru:{tag:'Метод', kicker:'Размер ≠ отсутствие смещения', q:'Очень большая выборка сама по себе устраняет confounding и систематические ошибки?', options:['Да, достаточно набрать много участников','Нет, большой n уменьшает случайную ошибку, но не исправляет дизайн'], right:1, answer:'Нет. Большая выборка может сузить случайную неопределённость вокруг систематически смещённой оценки.', caveat:'Размер выборки важен для точности и мощности, но не заменяет валидный дизайн и измерения.', design:'Методология причинного вывода.'},
      en:{tag:'Method', kicker:'Size ≠ absence of bias', q:'Does a very large sample automatically eliminate confounding and systematic bias?', options:['Yes, recruiting enough people solves it','No, a large n reduces random error but does not fix design'], right:1, answer:'No. A large sample can narrow random uncertainty around a systematically biased estimate.', caveat:'Sample size matters for precision and power, but does not replace valid design and measurement.', design:'Causal inference methodology.'},
      et:{tag:'Meetod', kicker:'Suurus ≠ kallutatuse puudumine', q:'Kas väga suur valim kõrvaldab automaatselt segavad tegurid ja süstemaatilise kallutatuse?', options:['Jah, piisab paljudest osalejatest','Ei, suur n vähendab juhuslikku viga, kuid ei paranda disaini'], right:1, answer:'Ei. Suur valim võib kitsendada juhuslikku ebakindlust süstemaatiliselt kallutatud hinnangu ümber.', caveat:'Valimi suurus on täpsuse ja võimsuse jaoks oluline, kuid ei asenda head disaini ja mõõtmist.', design:'Põhjusliku järeldamise metodoloogia.'}
    },
    {
      id:'confidence-interval', category:'method risk', level:3, source:'https://training.cochrane.org/handbook/current/chapter-06', sourceName:'Cochrane Handbook, Chapter 6',
      ru:{tag:'Риск', kicker:'Не только точечная оценка', q:'Достаточно ли сообщить «риск вырос на 30%», не показывая доверительный интервал и базовый риск?', options:['Да, 30% уже описывает эффект','Нет, без неопределённости и базы картина неполная'], right:1, answer:'Нет. Одна относительная точечная оценка скрывает статистическую неопределённость и абсолютный масштаб эффекта.', caveat:'Доверительный интервал в frequentist-подходе не означает 95% вероятность, что фиксированное истинное значение лежит внутри именно этого интервала.', design:'Руководство по представлению эффектов.'},
      en:{tag:'Risk', kicker:'Beyond the point estimate', q:'Is “risk increased by 30%” enough without a confidence interval and baseline risk?', options:['Yes, 30% describes the effect','No, the picture is incomplete without uncertainty and baseline'], right:1, answer:'No. A single relative point estimate hides both statistical uncertainty and the absolute scale of the effect.', caveat:'In frequentist inference, a confidence interval is not a 95% probability statement about a fixed true value lying in this particular interval.', design:'Guidance on presenting effects.'},
      et:{tag:'Risk', kicker:'Rohkem kui punktihinnang', q:'Kas piisab lausest „risk suurenes 30%“, kui usaldusvahemikku ja algriski ei näidata?', options:['Jah, 30% kirjeldab mõju','Ei, ilma ebakindluse ja algriskita on pilt puudulik'], right:1, answer:'Ei. Üks suhteline punktihinnang varjab nii statistilist ebakindlust kui ka mõju absoluutset suurust.', caveat:'Frequentistlikus käsitluses ei tähenda usaldusvahemik 95% tõenäosust, et fikseeritud tõeline väärtus asub just selles konkreetses vahemikus.', design:'Mõjude esitamise juhend.'}
    },
    {
      id:'observational-useless', category:'method', level:3, source:'https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/', sourceName:'Hernán & Robins, Causal Inference',
      ru:{tag:'Метод', kicker:'Иерархия не лестница', q:'Если исследование наблюдательное, значит ли это, что оно «ничего не доказывает» и его можно игнорировать?', options:['Да','Нет'], right:1, answer:'Нет. Наблюдательные данные могут быть единственно реалистичным или этичным способом изучить многие воздействия.', caveat:'Категория дизайна — начало оценки, а не финальный вердикт о качестве или причинности.', design:'Методология причинного вывода.'},
      en:{tag:'Method', kicker:'Hierarchy is not a ladder', q:'If a study is observational, does that mean it “proves nothing” and can be ignored?', options:['Yes','No'], right:1, answer:'No. Observational data may be the only realistic or ethical way to study many exposures.', caveat:'Study design is the start of appraisal, not a final verdict on quality or causality.', design:'Causal inference methodology.'},
      et:{tag:'Meetod', kicker:'Hierarhia pole lihtne redel', q:'Kui uuring on vaatluslik, kas see tähendab, et see „ei tõesta midagi“ ja seda võib eirata?', options:['Jah','Ei'], right:1, answer:'Ei. Vaatlusandmed võivad olla paljude kokkupuudete uurimiseks ainus realistlik või eetiline viis.', caveat:'Uuringudisain on hindamise algus, mitte lõplik otsus kvaliteedi või põhjuslikkuse kohta.', design:'Põhjusliku järeldamise metodoloogia.'}
    },
    {
      id:'relative-absolute', category:'method risk', level:3, source:'https://training.cochrane.org/handbook/current/chapter-15', sourceName:'Cochrane Handbook, Chapter 15',
      ru:{tag:'Риск', kicker:'Относительное ≠ абсолютное', q:'Рост риска «на 100%» обязательно означает большое абсолютное изменение?', options:['Да, 100% всегда очень много','Нет, всё зависит от исходного риска'], right:1, answer:'Нет. Рост с 1 до 2 случаев на 10 000 и с 10% до 20% — одинаковые +100% относительно, но совершенно разные абсолютные изменения.', caveat:'Относительные меры полезны, но лучше интерпретируются вместе с абсолютными величинами.', design:'Принцип коммуникации риска.'},
      en:{tag:'Risk', kicker:'Relative ≠ absolute', q:'Does a “100% increase in risk” necessarily mean a large absolute change?', options:['Yes, 100% is always huge','No, it depends on baseline risk'], right:1, answer:'No. Going from 1 to 2 cases per 10,000 and from 10% to 20% are both +100% relatively, but very different absolute changes.', caveat:'Relative measures are useful, but are easier to interpret alongside absolute quantities.', design:'Risk communication principle.'},
      et:{tag:'Risk', kicker:'Suhteline ≠ absoluutne', q:'Kas riski „100% suurenemine“ tähendab tingimata suurt absoluutset muutust?', options:['Jah, 100% on alati väga suur','Ei, see sõltub algriskist'], right:1, answer:'Ei. Muutus 1-lt 2 juhtumile 10 000 kohta ja 10%-lt 20%-le on mõlemal juhul suhteliselt +100%, kuid absoluutselt väga erinev.', caveat:'Suhtelised mõõdikud on kasulikud, kuid neid on parem tõlgendada koos absoluutsete suurustega.', design:'Riskikommunikatsiooni põhimõte.'}
    }
  ],
  glossary: [
    {term:{ru:'Абсолютный риск',en:'Absolute risk',et:'Absoluutne risk'},def:{ru:'Вероятность исхода в конкретной группе за определённый период.',en:'The probability of an outcome in a defined group over a specified period.',et:'Tulemuse tõenäosus kindlas rühmas kindla ajavahemiku jooksul.'}},
    {term:{ru:'Относительный риск (RR)',en:'Relative risk (RR)',et:'Suhteline risk (RR)'},def:{ru:'Отношение риска исхода в одной группе к риску в другой.',en:'The ratio of outcome risk in one group to outcome risk in another.',et:'Ühe rühma tulemuse riski suhe teise rühma riskiga.'}},
    {term:{ru:'Odds ratio (OR)',en:'Odds ratio (OR)',et:'Odds ratio (OR)'},def:{ru:'Отношение шансов исхода между группами. Это не процент и не то же самое, что RR.',en:'A ratio of outcome odds between groups. It is not a percentage and is not the same as RR.',et:'Tulemuse šansside suhe rühmade vahel. See pole protsent ega sama mis RR.'}},
    {term:{ru:'Confounding',en:'Confounding',et:'Segav tegur'},def:{ru:'Искажение связи из-за третьего фактора, связанного и с воздействием, и с исходом.',en:'Distortion of an association by a third factor related to both exposure and outcome.',et:'Seose moonutus kolmanda teguri tõttu, mis on seotud nii kokkupuute kui tulemusega.'}},
    {term:{ru:'Selection bias',en:'Selection bias',et:'Valikukallutatus'},def:{ru:'Систематическое искажение из-за того, кто попал в исследование или остался в нём.',en:'Systematic distortion caused by who enters or remains in a study.',et:'Süstemaatiline moonutus selle tõttu, kes uuringusse satub või sinna jääb.'}},
    {term:{ru:'Доверительный интервал',en:'Confidence interval',et:'Usaldusvahemik'},def:{ru:'Интервал оценок, отражающий неопределённость статистической процедуры при повторных выборках.',en:'A range of estimates reflecting uncertainty in a statistical procedure under repeated sampling.',et:'Hinnangute vahemik, mis peegeldab statistilise protseduuri ebakindlust korduvate valimite korral.'}},
    {term:{ru:'p-value',en:'p-value',et:'p-väärtus'},def:{ru:'Мера совместимости данных с заданной статистической моделью при её предпосылках; не вероятность истинности гипотезы.',en:'A measure of how compatible the data are with a specified statistical model under its assumptions; not the probability a hypothesis is true.',et:'Mõõt, kui kooskõlalised on andmed etteantud statistilise mudeliga selle eelduste korral; mitte hüpoteesi tõesuse tõenäosus.'}},
    {term:{ru:'Когортное исследование',en:'Cohort study',et:'Kohortuuring'},def:{ru:'Наблюдательный дизайн, где группы определяют по воздействию и отслеживают исходы во времени.',en:'An observational design where groups are defined by exposure and outcomes are followed over time.',et:'Vaatlusdisain, kus rühmad määratakse kokkupuute järgi ja tulemusi jälgitakse ajas.'}},
    {term:{ru:'Case-control',en:'Case-control study',et:'Juht-kontrolluuring'},def:{ru:'Дизайн, который начинает с людей с исходом и без него, а затем сравнивает прошлые воздействия.',en:'A design that starts with people with and without an outcome and compares prior exposures.',et:'Disain, mis alustab tulemusega ja tulemuseta inimestest ning võrdleb varasemaid kokkupuuteid.'}},
    {term:{ru:'RCT',en:'Randomised controlled trial (RCT)',et:'Randomiseeritud kontrolluuring (RCT)'},def:{ru:'Эксперимент, где участников случайно распределяют между вмешательствами, чтобы уменьшить систематические различия между группами.',en:'An experiment that randomly assigns participants to interventions to reduce systematic group differences.',et:'Katse, kus osalejad jaotatakse juhuslikult sekkumiste vahel, et vähendada rühmade süstemaatilisi erinevusi.'}},
    {term:{ru:'Мета-анализ',en:'Meta-analysis',et:'Meta-analüüs'},def:{ru:'Статистическое объединение результатов нескольких исследований, если их можно разумно совместить.',en:'Statistical combination of results from multiple studies when they can reasonably be combined.',et:'Mitme uuringu tulemuste statistiline ühendamine, kui neid saab mõistlikult kombineerida.'}},
    {term:{ru:'Гетерогенность',en:'Heterogeneity',et:'Heterogeensus'},def:{ru:'Различия между исследованиями по эффектам, популяциям, методам или другим характеристикам.',en:'Differences between studies in effects, populations, methods or other characteristics.',et:'Erinevused uuringute vahel mõju, populatsiooni, meetodite või muude omaduste poolest.'}}
  ]
};
