(() => {
  const D=window.ETO_DATA;if(!D?.ui)return;
  const t={
    ru:{navLearn:'Учиться',navToday:'Сегодня',navMap:'Карта знаний',navSimulator:'Симулятор',navProgress:'Прогресс',heroLearn:'Начать учиться',heroDaily:'Вопрос дня',newModesStat:'новых режимов',academyHomeEyebrow:'АКАДЕМИЯ',academyHomeTitle:'От фактов — к системе знаний.',academyHomeText:'Курсы, концепты, клинические кейсы, атлас функций, карта книг, ежедневные задачи и повторение.',courseCardTitle:'Мини-курсы',courseCardText:'Короткие маршруты по риску, дизайну исследований и веществам',mapCardTitle:'Карта знаний',mapCardText:'Связи между статистикой, мозгом, методами и веществами',dailyCardTitle:'Вопрос дня',dailyCardText:'Одна короткая задача на интерпретацию данных каждый день',simCardTitle:'Симулятор исследования',simCardText:'Собери дизайн и увидь, где появляется bias',myProgress:'Мой прогресс',chooseCourse:'Выбрать курс',academyCardTitle:'Открыть Академию',academyCardText:'Психопатология, когнитивная психология, нейропсихология, стресс, физиология и clinical reasoning',conceptCardTitle:'Концепты и кейсы',conceptCardText:'Новая база фундаментальных понятий и задач на рассуждение'},
    en:{navLearn:'Learn',navToday:'Today',navMap:'Knowledge map',navSimulator:'Simulator',navProgress:'Progress',heroLearn:'Start learning',heroDaily:'Daily question',newModesStat:'new modes',academyHomeEyebrow:'ACADEMY',academyHomeTitle:'From facts to a knowledge system.',academyHomeText:'Courses, concepts, clinical cases, functional atlas, book map, daily challenges and spaced review.',courseCardTitle:'Mini-courses',courseCardText:'Short paths through risk, study design and substances',mapCardTitle:'Knowledge map',mapCardText:'Connections across statistics, the brain, methods and substances',dailyCardTitle:'Daily question',dailyCardText:'One short evidence-interpretation task every day',simCardTitle:'Study simulator',simCardText:'Build a design and see where bias can enter',myProgress:'My progress',chooseCourse:'Choose a course',academyCardTitle:'Open Academy',academyCardText:'Psychopathology, cognitive psychology, neuropsychology, stress, physiology and clinical reasoning',conceptCardTitle:'Concepts & cases',conceptCardText:'A new foundation of core concepts and reasoning tasks'},
    et:{navLearn:'Õpi',navToday:'Täna',navMap:'Teadmiste kaart',navSimulator:'Simulaator',navProgress:'Edenemine',heroLearn:'Alusta õppimist',heroDaily:'Päeva küsimus',newModesStat:'uut režiimi',academyHomeEyebrow:'AKADEEMIA',academyHomeTitle:'Faktidest teadmiste süsteemini.',academyHomeText:'Kursused, mõisted, kliinilised juhtumid, funktsioonide atlas, raamatukaart, päevaülesanded ja kordamine.',courseCardTitle:'Minikursused',courseCardText:'Lühikesed rajad riski, uuringudisaini ja ainete teemal',mapCardTitle:'Teadmiste kaart',mapCardText:'Seosed statistika, aju, meetodite ja ainete vahel',dailyCardTitle:'Päeva küsimus',dailyCardText:'Üks lühike tõendusmaterjali tõlgendamise ülesanne päevas',simCardTitle:'Uuringusimulaator',simCardText:'Ehita disain ja vaata, kus kallutatus tekib',myProgress:'Minu edenemine',chooseCourse:'Vali kursus',academyCardTitle:'Ava Akadeemia',academyCardText:'Psühhopatoloogia, kognitiivne psühholoogia, neuropsühholoogia, stress, füsioloogia ja kliiniline mõtlemine',conceptCardTitle:'Mõisted ja juhtumid',conceptCardText:'Uus põhimõistete ja mõtlemisülesannete baas'}
  };
  ['ru','en','et'].forEach(l=>Object.assign(D.ui[l],t[l]));

  const firstGrid=document.querySelector('.learning-paths .path-grid');
  if(firstGrid&&!firstGrid.querySelector('[data-academy-entry]')){
    const a=document.createElement('a');a.className='path-card';a.href='academy.html';a.dataset.academyEntry='1';
    a.innerHTML='<span class="path-icon" aria-hidden="true">Ψ</span><h3 data-i18n="academyCardTitle">Открыть Академию</h3><p data-i18n="academyCardText">Психопатология, когнитивная психология, нейропсихология, стресс, физиология и clinical reasoning</p>';
    firstGrid.prepend(a);
    const b=document.createElement('a');b.className='path-card';b.href='concepts.html';b.dataset.academyEntry='1';
    b.innerHTML='<span class="path-icon" aria-hidden="true">◎</span><h3 data-i18n="conceptCardTitle">Концепты и кейсы</h3><p data-i18n="conceptCardText">Новая база фундаментальных понятий и задач на рассуждение</p>';
    firstGrid.append(b);
  }

  if(!document.querySelector('script[src="site-nav.js"]')){
    const s=document.createElement('script');s.src='site-nav.js';document.body.appendChild(s);
  }
})();