(() => {
  const D=window.ETO_DATA;if(!D?.ui)return;
  const t={
    ru:{navLearn:'Учиться',navToday:'Сегодня',navMap:'Карта знаний',navSimulator:'Симулятор',navProgress:'Прогресс',heroLearn:'Начать учиться',heroDaily:'Вопрос дня',newModesStat:'новых режимов',academyHomeEyebrow:'НОВЫЙ УРОВЕНЬ',academyHomeTitle:'Учись, исследуй, возвращайся.',academyHomeText:'Теперь сайт работает не только как библиотека, но и как учебная система: маршруты, карта тем, ежедневная задача, симулятор исследования и повторение.',courseCardTitle:'Мини-курсы',courseCardText:'Короткие маршруты по риску, дизайну исследований и веществам',mapCardTitle:'Карта знаний',mapCardText:'Связи между статистикой, мозгом, методами и веществами',dailyCardTitle:'Вопрос дня',dailyCardText:'Одна короткая задача на интерпретацию данных каждый день',simCardTitle:'Симулятор исследования',simCardText:'Собери дизайн и увидь, где появляется bias',myProgress:'Мой прогресс',chooseCourse:'Выбрать курс'},
    en:{navLearn:'Learn',navToday:'Today',navMap:'Knowledge map',navSimulator:'Simulator',navProgress:'Progress',heroLearn:'Start learning',heroDaily:'Daily question',newModesStat:'new modes',academyHomeEyebrow:'NEW LAYER',academyHomeTitle:'Learn, explore, return.',academyHomeText:'The site now works as a learning system as well as a library: guided paths, a knowledge map, a daily challenge, a study simulator and spaced review.',courseCardTitle:'Mini-courses',courseCardText:'Short paths through risk, study design and substances',mapCardTitle:'Knowledge map',mapCardText:'Connections across statistics, the brain, methods and substances',dailyCardTitle:'Daily question',dailyCardText:'One short evidence-interpretation task every day',simCardTitle:'Study simulator',simCardText:'Build a design and see where bias can enter',myProgress:'My progress',chooseCourse:'Choose a course'},
    et:{navLearn:'Õpi',navToday:'Täna',navMap:'Teadmiste kaart',navSimulator:'Simulaator',navProgress:'Edenemine',heroLearn:'Alusta õppimist',heroDaily:'Päeva küsimus',newModesStat:'uut režiimi',academyHomeEyebrow:'UUS TASE',academyHomeTitle:'Õpi, uuri, tule tagasi.',academyHomeText:'Sait toimib nüüd lisaks teegile ka õppesüsteemina: juhitud rajad, teadmiste kaart, päevaülesanne, uuringusimulaator ja kordamine.',courseCardTitle:'Minikursused',courseCardText:'Lühikesed rajad riski, uuringudisaini ja ainete teemal',mapCardTitle:'Teadmiste kaart',mapCardText:'Seosed statistika, aju, meetodite ja ainete vahel',dailyCardTitle:'Päeva küsimus',dailyCardText:'Üks lühike tõendusmaterjali tõlgendamise ülesanne päevas',simCardTitle:'Uuringusimulaator',simCardText:'Ehita disain ja vaata, kus kallutatus tekib',myProgress:'Minu edenemine',chooseCourse:'Vali kursus'}
  };
  ['ru','en','et'].forEach(l=>Object.assign(D.ui[l],t[l]));
})();
