(() => {
  'use strict';
  const SUP=['ru','en','et'];
  const getLang=()=>{try{const s=localStorage.getItem('eto-lang');if(SUP.includes(s))return s}catch{}return SUP.includes((navigator.language||'ru').slice(0,2))?(navigator.language||'ru').slice(0,2):'ru'};
  const t={
    ru:{title:'Лаборатории знаний',intro:'Мини-эксперименты показывают эффект до того, как дают ему название. Это учебные модели, не диагностические тесты.',memory:'Memory Lab',memoryText:'Прочитай слова 12 секунд. Затем список исчезнет — попробуй вспомнить как можно больше.',start:'Начать',ready:'Готово — ввести слова',placeholder:'Введи слова через запятую',check:'Проверить',remembered:'Совпало слов',memoryWhy:'Память зависит от кодирования и извлечения; результат одной попытки ничего не диагностирует.',attention:'Interference Lab',attentionText:'Отвечай на ЦВЕТ букв, а не на написанное слово.',round:'Раунд',correct:'Верно',wrong:'Ошибка',done:'Готово',time:'Время',accuracy:'Точность',attentionWhy:'Конкурирующая информация увеличивает требования к контролю внимания. Это демонстрация принципа, а не стандартизированный тест.',framing:'Framing Lab',framingText:'Один и тот же эффект можно описать несколькими способами.',baseline:'Базовый риск',after:'После воздействия',relative:'Относительное изменение',absolute:'Абсолютное изменение',per1000:'Дополнительных случаев на 1000',framingWhy:'Относительная мера может звучать драматично при небольшом абсолютном изменении. Полезно показывать обе.',mcda:'MCDA Playground',mcdaText:'Поменяй веса критериев и посмотри, как меняется итог. Числа ниже — вымышленные учебные данные, а не рейтинг реальных веществ.',health:'Физический вред',dependence:'Зависимость',social:'Социальный вред',weights:'Веса',score:'Итог',mcdaWhy:'MCDA не обнаруживает единственную “истинную опасность”: результат зависит от критериев, шкал и весов.',illustrative:'Иллюстративные данные'},
    en:{title:'Knowledge labs',intro:'Mini-experiments show an effect before naming it. These are learning models, not diagnostic tests.',memory:'Memory Lab',memoryText:'Read the words for 12 seconds. Then they disappear—recall as many as you can.',start:'Start',ready:'Ready — enter words',placeholder:'Enter words separated by commas',check:'Check',remembered:'Words matched',memoryWhy:'Memory depends on encoding and retrieval; one attempt has no diagnostic meaning.',attention:'Interference Lab',attentionText:'Respond to the LETTER COLOUR, not the word.',round:'Round',correct:'Correct',wrong:'Wrong',done:'Done',time:'Time',accuracy:'Accuracy',attentionWhy:'Competing information increases demands on attentional control. This is a principle demo, not a standardised test.',framing:'Framing Lab',framingText:'The same effect can be described in several formats.',baseline:'Baseline risk',after:'After exposure',relative:'Relative change',absolute:'Absolute change',per1000:'Additional cases per 1,000',framingWhy:'A relative measure can sound dramatic when the absolute change is small. Showing both is more informative.',mcda:'MCDA Playground',mcdaText:'Change criterion weights and watch totals change. The numbers below are invented teaching data, not rankings of real substances.',health:'Physical harm',dependence:'Dependence',social:'Social harm',weights:'Weights',score:'Total',mcdaWhy:'MCDA does not discover one “true danger”: results depend on criteria, scales and weights.',illustrative:'Illustrative data'},
    et:{title:'Teadmiste laborid',intro:'Minieksperimendid näitavad efekti enne selle nimetamist. Need on õpimudelid, mitte diagnostilised testid.',memory:'Mälu labor',memoryText:'Loe sõnu 12 sekundit. Siis need kaovad—proovi meenutada nii palju kui võimalik.',start:'Alusta',ready:'Valmis — sisesta sõnad',placeholder:'Sisesta sõnad komadega',check:'Kontrolli',remembered:'Kattuvaid sõnu',memoryWhy:'Mälu sõltub kodeerimisest ja meenutamisest; ühe katse tulemus pole diagnostiline.',attention:'Interferentsi labor',attentionText:'Vasta TÄHTEDE VÄRVILE, mitte kirjutatud sõnale.',round:'Voor',correct:'Õige',wrong:'Vale',done:'Valmis',time:'Aeg',accuracy:'Täpsus',attentionWhy:'Konkureeriv info suurendab tähelepanukontrolli nõudmisi. See on põhimõtte demonstratsioon, mitte standardtest.',framing:'Raamistamise labor',framingText:'Sama mõju saab kirjeldada mitmel viisil.',baseline:'Algrisk',after:'Pärast kokkupuudet',relative:'Suhteline muutus',absolute:'Absoluutne muutus',per1000:'Lisajuhte 1000 kohta',framingWhy:'Suhteline näit võib kõlada dramaatiliselt, kui absoluutne muutus on väike. Mõlemat tasub näidata.',mcda:'MCDA mänguväljak',mcdaText:'Muuda kriteeriumide kaale ja vaata, kuidas koguskoor muutub. Allolevad arvud on väljamõeldud õppeandmed, mitte päris ainete pingerida.',health:'Füüsiline kahju',dependence:'Sõltuvus',social:'Sotsiaalne kahju',weights:'Kaalud',score:'Koguskoor',mcdaWhy:'MCDA ei leia üht “tõelist ohtu”: tulemus sõltub kriteeriumidest, skaaladest ja kaaludest.',illustrative:'Illustratiivsed andmed'}
  };
  let lang=getLang();const tr=k=>t[lang]?.[k]||t.ru[k]||k;const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const WORDS={ru:['яблоко','река','окно','зелёный','собака','лампа','музыка','камень','облако','книга','мост','часы'],en:['apple','river','window','green','dog','lamp','music','stone','cloud','book','bridge','clock'],et:['õun','jõgi','aken','roheline','koer','lamp','muusika','kivi','pilv','raamat','sild','kell']};
  function labels(){document.documentElement.lang=lang;$$('[data-lab]').forEach(e=>e.textContent=tr(e.dataset.lab));$$('[data-lab-placeholder]').forEach(e=>e.placeholder=tr(e.dataset.labPlaceholder));renderFraming();renderMCDA()}
  function memory(){const start=$('#memoryStart'),stage=$('#memoryStage'),input=$('#memoryInput'),check=$('#memoryCheck'),result=$('#memoryResult');if(!start)return;let active=[];start.onclick=()=>{active=[...WORDS[lang]];stage.textContent=active.join(' · ');input.hidden=true;check.hidden=true;result.textContent='';start.disabled=true;setTimeout(()=>{stage.textContent='•••';input.hidden=false;check.hidden=false;input.focus()},12000)};check.onclick=()=>{const entered=input.value.toLocaleLowerCase(lang).split(/[,;\n]+/).map(s=>s.trim()).filter(Boolean);const set=new Set(active.map(x=>x.toLocaleLowerCase(lang)));const hit=new Set(entered.filter(x=>set.has(x)));result.innerHTML=`<strong>${tr('remembered')}: ${hit.size}/${active.length}</strong><p>${tr('memoryWhy')}</p>`;start.disabled=false}}
  function attention(){const mount=$('#attentionTask');if(!mount)return;const words={ru:['КРАСНЫЙ','СИНИЙ','ЗЕЛЁНЫЙ'],en:['RED','BLUE','GREEN'],et:['PUNANE','SININE','ROHELINE']};const colors=['red','blue','green'];let round=0,correct=0,start=0,current='';const colorCSS={red:'#c94040',blue:'#3675c5',green:'#2f8a56'};const draw=()=>{if(round>=9){const sec=((performance.now()-start)/1000).toFixed(1);mount.innerHTML=`<div class="lab-result"><strong>${tr('done')}</strong><p>${tr('time')}: ${sec}s · ${tr('accuracy')}: ${Math.round(correct/9*100)}%</p><p>${tr('attentionWhy')}</p></div><button class="btn primary" id="attentionRestart">${tr('start')}</button>`;$('#attentionRestart').onclick=begin;return}const w=words[lang][Math.floor(Math.random()*3)];current=colors[Math.floor(Math.random()*3)];mount.innerHTML=`<div class="stroop-word" style="color:${colorCSS[current]}">${w}</div><div class="stroop-actions">${colors.map(c=>`<button class="case-option" data-color="${c}" style="border-color:${colorCSS[c]}">${c==='red'?(lang==='ru'?'Красный':lang==='et'?'Punane':'Red'):c==='blue'?(lang==='ru'?'Синий':lang==='et'?'Sinine':'Blue'):(lang==='ru'?'Зелёный':lang==='et'?'Roheline':'Green')}</button>`).join('')}</div><small>${tr('round')} ${round+1}/9</small>`;$$('[data-color]',mount).forEach(b=>b.onclick=()=>{if(b.dataset.color===current)correct++;round++;draw()})};const begin=()=>{round=0;correct=0;start=performance.now();draw()};mount.innerHTML=`<button class="btn primary" id="attentionBegin">${tr('start')}</button>`;$('#attentionBegin').onclick=begin}
  function renderFraming(){const b=Number($('#frameBase')?.value||2),rr=Number($('#frameRR')?.value||2),after=Math.min(100,b*rr),abs=after-b,rel=b?((after/b-1)*100):0;$('#frameBaseV')&&( $('#frameBaseV').textContent=`${b.toFixed(1)}%`);$('#frameRRV')&&( $('#frameRRV').textContent=`${rr.toFixed(1)}×`);$('#frameOutput')&&( $('#frameOutput').innerHTML=`<div><span>${tr('baseline')}</span><strong>${b.toFixed(1)}%</strong></div><div><span>${tr('after')}</span><strong>${after.toFixed(1)}%</strong></div><div><span>${tr('relative')}</span><strong>${rel>=0?'+':''}${rel.toFixed(0)}%</strong></div><div><span>${tr('absolute')}</span><strong>${abs>=0?'+':''}${abs.toFixed(1)} pp</strong></div><div><span>${tr('per1000')}</span><strong>${Math.round(abs*10)}</strong></div>`)}
  function framing(){['frameBase','frameRR'].forEach(id=>$('#'+id)?.addEventListener('input',renderFraming));renderFraming()}
  const demo=[{name:'A',health:8,dependence:3,social:2},{name:'B',health:4,dependence:8,social:5},{name:'C',health:3,dependence:4,social:9}];
  function renderMCDA(){const w={health:Number($('#wHealth')?.value||40),dependence:Number($('#wDependence')?.value||30),social:Number($('#wSocial')?.value||30)},sum=w.health+w.dependence+w.social||1;$('#wHealthV')&&( $('#wHealthV').textContent=w.health);$('#wDependenceV')&&( $('#wDependenceV').textContent=w.dependence);$('#wSocialV')&&( $('#wSocialV').textContent=w.social);const rows=demo.map(x=>({...x,total:(x.health*w.health+x.dependence*w.dependence+x.social*w.social)/sum})).sort((a,b)=>b.total-a.total);$('#mcdaOutput')&&( $('#mcdaOutput').innerHTML=rows.map(x=>`<div class="mcda-row"><strong>${x.name}</strong><span>${tr('score')}: ${x.total.toFixed(1)}</span></div>`).join(''))}
  function mcda(){['wHealth','wDependence','wSocial'].forEach(id=>$('#'+id)?.addEventListener('input',renderMCDA));renderMCDA()}
  $('#languageSelect')?.addEventListener('change',e=>{lang=e.target.value;setTimeout(()=>{labels();attention()},0)});labels();memory();attention();framing();mcda();
})();