(() => {
  const A=window.ETO_ACADEMY;if(!A?.courses)return;
  const courses=[
    {id:'psychopathology-foundations',icon:'Ψ',color:'design',title:{ru:'Основы психопатологии',en:'Foundations of psychopathology',et:'Psühhopatoloogia alused'},desc:{ru:'Феноменология, восприятие, мышление и insight без прыжка от симптома к диагнозу.',en:'Phenomenology, perception, thought and insight without jumping from symptom to diagnosis.',et:'Fenomenoloogia, taju, mõtlemine ja haigusteadlikkus ilma sümptomist kohe diagnoosini hüppamata.'},lessons:[
      {id:'phenomenology',title:{ru:'Сначала описать феномен',en:'Describe the phenomenon first',et:'Kirjelda esmalt nähtust'},body:{ru:'Клиническое мышление начинается с точного описания переживания: что происходит, когда, как часто, в каком состоянии и как человек это понимает. Название диагноза — более поздний уровень вывода.',en:'Clinical reasoning starts with precise description: what happens, when, how often, in what state, and how the person understands it. Diagnostic labels belong later in the inference chain.',et:'Kliiniline mõtlemine algab täpsest kirjeldusest: mis toimub, millal, kui sageli, millises seisundis ja kuidas inimene seda mõistab. Diagnoosisilt tuleb järeldusahelas hiljem.'}},
      {id:'perception',title:{ru:'Галлюцинация и иллюзия',en:'Hallucination and illusion',et:'Hallutsinatsioon ja illusioon'},body:{ru:'Иллюзия — ошибочная интерпретация реального стимула; галлюцинация — перцептивный опыт без соответствующего внешнего стимула. Но ни одно слово само по себе не устанавливает диагноз.',en:'An illusion misinterprets a real stimulus; a hallucination is a perceptual experience without a matching external stimulus. Neither term establishes a diagnosis by itself.',et:'Illusioon on reaalse stiimuli väär tõlgendus; hallutsinatsioon on tajukogemus ilma vastava välise stiimulita. Kumbki mõiste ei määra iseenesest diagnoosi.'}},
      {id:'insight',title:{ru:'Insight — не переключатель',en:'Insight is not a switch',et:'Haigusteadlikkus pole lüliti'},body:{ru:'Критика к состоянию может быть частичной, неодинаковой для разных переживаний и меняться со временем. Поэтому “есть/нет insight” часто слишком грубое описание.',en:'Insight can be partial, differ across experiences and change over time. A simple present/absent label is often too coarse.',et:'Haigusteadlikkus võib olla osaline, kogemuste vahel erineda ja ajas muutuda. Lihtne olemas/puudub jaotus on sageli liiga jäme.'}}
    ]},
    {id:'cognitive-science',icon:'◎',color:'stats',title:{ru:'Как работает познание',en:'How cognition works',et:'Kuidas tunnetus töötab'},desc:{ru:'Внимание, рабочая память, реконструкция воспоминаний и эвристики.',en:'Attention, working memory, reconstructive memory and heuristics.',et:'Tähelepanu, töömälu, rekonstruktiivne mälu ja heuristikud.'},lessons:[
      {id:'attention',title:{ru:'Внимание — ограниченный ресурс',en:'Attention is capacity-limited',et:'Tähelepanu maht on piiratud'},body:{ru:'Мы не обрабатываем всё одинаково глубоко. Цели, конкурирующие стимулы, сон и нагрузка меняют то, что получает приоритет.',en:'We do not process everything equally deeply. Goals, competing stimuli, sleep and load change what receives priority.',et:'Me ei töötle kõike võrdselt sügavalt. Eesmärgid, konkureerivad stiimulid, uni ja koormus muudavad prioriteete.'}},
      {id:'working-memory',title:{ru:'Рабочая память — это обработка',en:'Working memory is active processing',et:'Töömälu on aktiivne töötlemine'},body:{ru:'Рабочая память нужна, когда информацию надо временно удерживать и одновременно использовать. Это не просто “короткая полка хранения”.',en:'Working memory is used when information must be temporarily maintained and manipulated. It is more than a short storage shelf.',et:'Töömälu on vajalik, kui infot tuleb ajutiselt hoida ja samal ajal kasutada. See on rohkem kui lühiajaline hoiuriiul.'}},
      {id:'reconstruction',title:{ru:'Память реконструируется',en:'Memory is reconstructed',et:'Mälu rekonstrueeritakse'},body:{ru:'Воспоминание меняется под влиянием контекста извлечения, ожиданий и последующей информации. Это не делает память “бесполезной”, но требует осторожности в интерпретации.',en:'Retrieval is shaped by context, expectations and later information. This does not make memory useless, but it does demand caution in interpretation.',et:'Meenutamist kujundavad kontekst, ootused ja hilisem info. See ei tee mälu kasutuks, kuid nõuab tõlgendamisel ettevaatust.'}}
    ]},
    {id:'neuropsychology',icon:'⌁',color:'design',title:{ru:'Нейропсихология без мифа о “центрах”',en:'Neuropsychology beyond “centres”',et:'Neuropsühholoogia ilma “keskuste” müüdita'},desc:{ru:'Сети, афазия, неглект и почему локализация — это не карта с одной кнопкой на функцию.',en:'Networks, aphasia, neglect and why localisation is not a one-button-per-function map.',et:'Võrgustikud, afaasia, neglect ja miks lokaliseerimine pole üks-nupp-ühele-funktsioonile kaart.'},lessons:[
      {id:'networks',title:{ru:'Функции распределены по сетям',en:'Functions live in networks',et:'Funktsioonid paiknevad võrgustikes'},body:{ru:'Мозговая функция обычно зависит от нескольких узлов и связей. Повреждение одного участка может нарушить работу всей системы.',en:'Brain functions typically depend on several nodes and connections. Damage to one region can disrupt the wider system.',et:'Ajufunktsioonid sõltuvad tavaliselt mitmest sõlmest ja ühendusest. Ühe piirkonna kahjustus võib häirida kogu süsteemi.'}},
      {id:'aphasia',title:{ru:'Афазию полезно разбирать по компонентам',en:'Aphasia is better decomposed',et:'Afaasiat tasub lahutada komponentideks'},body:{ru:'Понимание, называние, повторение, беглость, чтение и письмо могут нарушаться по-разному; классические синдромные ярлыки не исчерпывают картину.',en:'Comprehension, naming, repetition, fluency, reading and writing can be affected differently; classic syndrome labels do not capture everything.',et:'Mõistmine, nimetamine, kordamine, soravus, lugemine ja kirjutamine võivad erineda; klassikalised sündroomisildid ei kirjelda kõike.'}},
      {id:'neglect',title:{ru:'Не замечать ≠ не видеть',en:'Not noticing ≠ not seeing',et:'Mitte märkama ≠ mitte nägema'},body:{ru:'Пространственный неглект показывает, что нарушение внимания может выглядеть как потеря части мира даже при сохранности первичных сенсорных путей.',en:'Spatial neglect shows how an attentional disorder can look like loss of part of the world even when primary sensory pathways are relatively preserved.',et:'Ruumiline neglect näitab, kuidas tähelepanuhäire võib näida osa maailma kadumisena ka siis, kui esmased sensoorsed rajad on suhteliselt säilinud.'}}
    ]},
    {id:'stress-physiology',icon:'↯',color:'substances',title:{ru:'Стресс, сон и физиология',en:'Stress, sleep and physiology',et:'Stress, uni ja füsioloogia'},desc:{ru:'HPA-ось, автономная регуляция, циркадные ритмы и аллостаз.',en:'HPA axis, autonomic regulation, circadian rhythms and allostasis.',et:'HPA-telg, autonoomne regulatsioon, ööpäevarütmid ja allostaas.'},lessons:[
      {id:'acute',title:{ru:'Стрессовая реакция может быть адаптивной',en:'Stress responses can be adaptive',et:'Stressivastus võib olla kohastumuslik'},body:{ru:'Кратковременная мобилизация помогает реагировать на нагрузку. Риск зависит от интенсивности, длительности, повторяемости и восстановления.',en:'Short-term mobilisation helps meet demands. Risk depends on intensity, duration, repetition and recovery.',et:'Lühiajaline mobilisatsioon aitab nõudmistega toime tulla. Risk sõltub intensiivsusest, kestusest, kordumisest ja taastumisest.'}},
      {id:'cortisol',title:{ru:'Кортизол — не “стрессометр”',en:'Cortisol is not a “stress meter”',et:'Kortisool pole “stressimõõtja”'},body:{ru:'Кортизол имеет суточную динамику и много физиологических ролей. Один анализ без времени, контекста и референсных значений мало говорит о психологическом стрессе.',en:'Cortisol follows circadian dynamics and serves many physiological roles. One value without timing, context and reference ranges says little about psychological stress.',et:'Kortisoolil on ööpäevane dünaamika ja palju füsioloogilisi rolle. Üks näit ilma aja, konteksti ja referentsväärtusteta ütleb psühholoogilise stressi kohta vähe.'}},
      {id:'allostasis',title:{ru:'Стабильность через изменение',en:'Stability through change',et:'Stabiilsus muutuse kaudu'},body:{ru:'Аллостаз описывает адаптивную перестройку регуляции под ситуацию. Аллостатическая нагрузка — полезная рамка, но не единый универсальный клинический показатель.',en:'Allostasis describes adaptive adjustment of regulation to context. Allostatic load is a useful framework, not one universal clinical measure.',et:'Allostaas kirjeldab regulatsiooni kohastuvat muutmist vastavalt kontekstile. Allostaatiline koormus on kasulik raamistik, mitte üks universaalne kliiniline näit.'}}
    ]},
    {id:'clinical-reasoning',icon:'⌕',color:'stats',title:{ru:'Клиническое рассуждение',en:'Clinical reasoning',et:'Kliiniline mõtlemine'},desc:{ru:'Как собирать данные, строить differential и не подтверждать первую гипотезу.',en:'How to gather data, build a differential and avoid confirming the first hypothesis.',et:'Kuidas koguda andmeid, ehitada diferentsiaali ja vältida esimese hüpoteesi kinnitamist.'},lessons:[
      {id:'open',title:{ru:'Сначала открытый вопрос',en:'Start open-ended',et:'Alusta avatud küsimusega'},body:{ru:'Открытый вопрос даёт человеку возможность задать структуру ответа. Уточняющие вопросы полезнее задавать после первичного описания, а не подменять ими рассказ.',en:'An open question lets the person shape the initial account. Focused clarification is most useful after the first description rather than replacing it.',et:'Avatud küsimus laseb inimesel esmase kirjelduse ise kujundada. Täpsustavad küsimused on kõige kasulikumad pärast esmast kirjeldust.'}},
      {id:'neutral',title:{ru:'Не подсказывай ответ',en:'Do not feed the answer',et:'Ära anna vastust ette'},body:{ru:'Наводящая формулировка может менять ответ и усиливать confirmation bias интервьюера. Нейтральность улучшает качество данных.',en:'Leading wording can change responses and amplify interviewer confirmation bias. Neutral wording improves data quality.',et:'Suunav sõnastus võib vastust muuta ja tugevdada intervjueerija kinnituskallutatust. Neutraalne sõnastus parandab andmete kvaliteeti.'}},
      {id:'differential',title:{ru:'Держи несколько гипотез',en:'Keep multiple hypotheses alive',et:'Hoia mitu hüpoteesi korraga'},body:{ru:'Differential reasoning сравнивает альтернативные объяснения и ищет данные, которые их различают. Это эффективнее, чем собирать только подтверждения любимой версии.',en:'Differential reasoning compares alternative explanations and seeks discriminating evidence. That is better than collecting only support for a favoured hypothesis.',et:'Diferentsiaalne mõtlemine võrdleb alternatiivseid seletusi ja otsib neid eristavaid andmeid. See on parem kui ainult lemmikhüpoteesi toetuse kogumine.'}}
    ]},
    {id:'psychopharm-principles',icon:'⚗',color:'substances',title:{ru:'Принципы психофармакологии',en:'Principles of psychopharmacology',et:'Psühhofarmakoloogia põhimõtted'},desc:{ru:'Рецепторы, доза, адаптация и почему механизм не равен клиническому эффекту.',en:'Receptors, dose, adaptation and why mechanism is not the same as clinical effect.',et:'Retseptorid, annus, kohanemine ja miks mehhanism ei võrdu kliinilise toimega.'},lessons:[
      {id:'receptor',title:{ru:'Рецептор — начало цепочки',en:'A receptor is the start of a chain',et:'Retseptor on ahela algus'},body:{ru:'Связывание с рецептором запускает клеточные и сетевые последствия, но итог зависит от распределения рецепторов, дозы, фармакокинетики и состояния системы.',en:'Receptor binding starts cellular and network consequences, but the result depends on receptor distribution, dose, pharmacokinetics and system state.',et:'Retseptoriga seondumine käivitab rakulised ja võrgustikulised tagajärjed, kuid tulemus sõltub retseptorite jaotusest, annusest, farmakokineetikast ja süsteemi seisundist.'}},
      {id:'adaptation',title:{ru:'Мозг адаптируется во времени',en:'The brain adapts over time',et:'Aju kohaneb ajas'},body:{ru:'Острый молекулярный эффект и эффект после недель воздействия могут различаться из-за регуляции рецепторов, экспрессии генов и перестройки сетей.',en:'Acute molecular effects and effects after weeks of exposure can differ because of receptor regulation, gene expression and network adaptation.',et:'Äge molekulaarne toime ja nädalatepikkuse kokkupuute mõju võivad erineda retseptorregulatsiooni, geeniekspressiooni ja võrgustiku kohanemise tõttu.'}},
      {id:'clinical',title:{ru:'Клинические исходы требуют клинических данных',en:'Clinical outcomes require clinical evidence',et:'Kliinilised tulemused vajavad kliinilisi andmeid'},body:{ru:'Механистическая правдоподобность не заменяет данные о пользе, вреде, сравнении с альтернативами и конкретной популяции.',en:'Mechanistic plausibility does not replace evidence about benefit, harm, alternatives and the population being treated.',et:'Mehhanistlik usutavus ei asenda tõendeid kasu, kahju, alternatiivide ja konkreetse populatsiooni kohta.'}}
    ]}
  ];
  const existing=new Set(A.courses.map(c=>c.id));courses.forEach(c=>{if(!existing.has(c.id))A.courses.push(c)});
})();