(() => {
  'use strict';
  const W=window.ETO_WORKSHOP,K=window.ETO_KNOWLEDGE,M=window.ETO_MODELS,A=window.ETO_ACTIVITIES;
  if(!W||!K||!M||!A)return;
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const t=(ru,en,et)=>({ru,en,et});
  const words={
    title:t('Читай. Проверяй. Соединяй.','Read. Test. Connect.','Loe. Kontrolli. Seosta.'),
    intro:t('10 маршрутов по твоей библиотеке: от короткого объяснения к применению. Ниже — четыре интерактива, где можно проверить интуицию.','10 routes through your library: from a short explanation to application. Four activities below let you test your intuition.','10 rada läbi sinu raamatukogu: lühiselgitusest rakendamiseni. Allpool saad nelja tegevusega oma intuitsiooni kontrollida.'),
    workshop:t('Практикум','Workshop','Praktikum'),routes:t('Маршруты чтения','Reading routes','Lugemisrajad'),labs:t('Попробуй сам','Try it yourself','Proovi ise'),
    basis:t('Авторские учебные материалы по темам библиотеки. Книги — ориентиры для чтения; открытые источники указаны в каждом разборе. Текст и иллюстрации книг не воспроизводятся.','Original learning material on your library’s topics. Books are reading guides; open references appear in each lesson. Book text and illustrations are not reproduced.','Algsed õppematerjalid sinu raamatukogu teemadel. Raamatud on lugemissuunised; iga teema juures on avalikud allikad. Raamatute tekste ega illustratsioone ei taasesitata.'),
    all:t('Все темы','All topics','Kõik teemad'),search:t('Найти тему или книгу','Find a topic or book','Leia teema või raamat'),empty:t('Ничего не найдено. Измени запрос или выбери все темы.','No matches. Change your query or select all topics.','Vasteid pole. Muuda otsingut või vali kõik teemad.'),
    idea:t('Разберись','Understand','Mõista'),example:t('Разбери пример','Work through an example','Uuri näidet'),limit:t('Не перепутай','Watch the distinction','Ära aja segamini'),task:t('Примени идею','Apply the idea','Rakenda mõtet'),
    confidence:t('Насколько уверен в ответе?','How confident are you?','Kui kindel oled vastuses?'),low:t('Пока сомневаюсь','Not sure yet','Pole veel kindel'),mid:t('Скорее уверен','Fairly confident','Üsna kindel'),high:t('Очень уверен','Very confident','Väga kindel'),
    correct:t('Верно','Correct','Õige'),wrong:t('Стоит пересмотреть','Reconsider this','Vaata uuesti üle'),calibration:t('Высокая уверенность не совпала с ответом. Сравни свою логику с объяснением.','High confidence did not match the answer. Compare your reasoning with the explanation.','Suur kindlus ei vastanud tulemusele. Võrdle oma arutlust selgitusega.'),
    retry:t('Попробовать снова','Try again','Proovi uuesti'),back:t('Все маршруты','All routes','Kõik rajad'),next:t('Следующий маршрут','Next route','Järgmine rada'),
    books:t('Связанные книги','Related books','Seotud raamatud'),references:t('Открытые источники','Open references','Avalikud allikad'),concepts:t('Связанные понятия','Related concepts','Seotud mõisted'),
    note:t('Моя заметка: объясни идею своим примером','My note: explain the idea with your own example','Minu märge: selgita mõtet oma näitega'),saved:t('Сохранено в этом браузере','Saved in this browser','Salvestatud sellesse brauserisse'),saveError:t('Браузер не сохранил изменения. Они останутся только до закрытия страницы.','The browser could not save changes. They will last only until this page closes.','Brauser ei saanud muudatusi salvestada. Need säilivad ainult lehe sulgemiseni.'),
    progress:t('Маршрутов с верным последним ответом','Routes with a correct latest answer','Radu, mille viimane vastus oli õige'),min:t('мин','min','min'),open:t('Открыть маршрут','Open route','Ava rada'),
    bayes:t('Когда сигнал обманывает интуицию','When a signal fools intuition','Kui signaal eksitab intuitsiooni'),
    bayesText:t('Учебный контроль качества 1000 деталей. Меняй долю дефектов и свойства детектора. Числа вымышлены; дроби — ожидаемые количества, не реальные детали.','A teaching model of quality control for 1,000 parts. Change defect prevalence and detector properties. Values are fictional; fractions are expected counts, not actual parts.','1000 detaili kvaliteedikontrolli õppemudel. Muuda defektide osakaalu ja detektori omadusi. Arvud on väljamõeldud; murrud on oodatavad kogused, mitte päris detailid.'),
    prevalence:t('Доля дефектных деталей','Defective parts','Defektsete detailide osakaal'),sensitivity:t('Обнаруживает дефектные','Detects defective parts','Tuvastab defektsed detailid'),specificity:t('Правильно пропускает исправные','Correctly passes good parts','Laseb korras detailid õigesti läbi'),
    tp:t('Дефект + сигнал','Defect + signal','Defekt + signaal'),fp:t('Исправна + сигнал','Good + signal','Korras + signaal'),fn:t('Дефект без сигнала','Defect, no signal','Defekt, signaal puudub'),tn:t('Исправна без сигнала','Good, no signal','Korras, signaal puudub'),ppv:t('Доля дефектов среди сигналов','Defects among signals','Defektide osakaal signaalide seas'),undefined:t('Нет сигналов — доля не определена','No signals — proportion undefined','Signaale pole – osakaal määramata'),
    bayesWhy:t('Знаменатель — все сигналы, включая ложные. Высокая чувствительность не равна вероятности дефекта после сигнала. Попробуй уменьшить базовую частоту при неизменном детекторе.','The denominator includes all signals, including false alarms. High sensitivity is not the probability of a defect after a signal. Try reducing prevalence while leaving the detector unchanged.','Nimetaja hõlmab kõiki signaale, ka valehäireid. Suur tundlikkus ei võrdu defekti tõenäosusega pärast signaali. Vähenda levimust detektorit muutmata.'),
    receptor:t('Рецептор: занятость и ответ','Receptor: occupancy and response','Retseptor: hõivatus ja vastus'),concentration:t('Концентрация C · условные единицы','Concentration C · arbitrary units','Kontsentratsioon C · tingühikud'),kd:t('Kd · условные единицы','Kd · arbitrary units','Kd · tingühikud'),efficacy:t('Внутренняя активность α','Intrinsic activity α','Sisemine aktiivsus α'),occupancy:t('Занято рецепторов','Receptor occupancy','Retseptorite hõivatus'),response:t('Ответ модели','Model response','Mudeli vastus'),
    receptorText:t('Один тип независимых мест связывания, равновесие: занятость = C/(C + Kd). Условный ответ = α × занятость. Это упрощение без рецепторного резерва, не расчёт доз и не модель конкретного препарата.','One type of independent binding site at equilibrium: occupancy = C/(C + Kd). Illustrative response = α × occupancy. This omits receptor reserve; it is not a dose calculator or a model of a specific medicine.','Üks sõltumatute seondumiskohtade tüüp tasakaalus: hõivatus = C/(C + Kd). Tinglik vastus = α × hõivatus. Retseptorireserv puudub; see pole annusekalkulaator ega konkreetse ravimi mudel.'),
    receptorWhy:t('При C = Kd занята половина мест. Меняя α, можно изменить ответ без изменения занятости. Реальная фармакодинамика сложнее этой модели.','At C = Kd half the sites are occupied. Changing α alters the response without changing occupancy. Real pharmacodynamics is more complex than this model.','Kui C = Kd, on pooled kohad hõivatud. α muutmine muudab vastust ilma hõivatust muutmata. Tegelik farmakodünaamika on keerukam.'),
    consequences:t('Добавили или убрали?','Added or removed?','Lisati või eemaldati?'),consequencesText:t('Четыре ситуации: определи, что произошло со стимулом и с частотой поведения.','Four scenarios: identify what happened to the stimulus and behaviour frequency.','Neli olukorda: määra, mis juhtus stiimuli ja käitumise sagedusega.'),
    interview:t('Следующий вопрос','The next question','Järgmine küsimus'),interviewText:t('Четыре вымышленных учебных ситуации. Выбирай уточнение, которое даёт информацию, не навязывая объяснение.','Four fictional learning scenarios. Choose a follow-up that adds information without imposing an explanation.','Neli väljamõeldud õppeolukorda. Vali täpsustus, mis lisab teavet ilma seletust peale surumata.'),
    nextCase:t('Дальше','Continue','Edasi'),restart:t('Начать заново','Start again','Alusta uuesti'),result:t('Результат раунда','Round result','Vooru tulemus'),completed:t('Все ситуации разобраны. Посмотри объяснения или начни заново.','All scenarios reviewed. Check the explanations or start again.','Kõik olukorrad on läbi vaadatud. Vaata selgitusi või alusta uuesti.'),reset:t('Сбросить фильтры','Reset filters','Lähtesta filtrid')
  };
  let lang=window.ETO_LEARNING.getLang();
  const tx=o=>o?.[lang]||o?.ru||'',tr=k=>tx(words[k]);
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const KEY='eto-workshop-v1';
  let state={answers:{},notes:{}};
  try{const parsed=JSON.parse(localStorage.getItem(KEY));if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed)){for(const key of ['answers','notes'])if(parsed[key]&&typeof parsed[key]==='object'&&!Array.isArray(parsed[key]))state[key]=parsed[key]}}catch{}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{return false}}
  let domain='all',search='',active=new URLSearchParams(location.search).get('topic')||'';
  const runs={consequences:{index:0,answers:[]},interview:{index:0,answers:[]}};
  const sliderState={prevalence:1,sensitivity:90,specificity:95,concentration:5,kd:5,efficacy:1};
  const answered=m=>{const a=state.answers[m.id];return a&&Number.isInteger(a.selected)&&a.selected>=0&&a.selected<m.options.length?a:null};
  const link=(url,label)=>`<a href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(label)} ↗</a>`;
  function progress(){const n=W.modules.filter(m=>answered(m)?.selected===m.right).length;$('#workshopProgress').textContent=`${tr('progress')}: ${n}/${W.modules.length}`}
  function renderCards(){
    const needle=search.trim().toLocaleLowerCase(lang);
    const list=W.modules.filter(m=>(domain==='all'||m.domain===domain)&&(!needle||[tx(m.title),tx(m.lead),...m.books.map(id=>{const b=K.books.find(b=>b.id===id);return `${b?.title||''} ${b?.author||''}`})].join(' ').toLocaleLowerCase(lang).includes(needle)));
    $('#routeGrid').innerHTML=list.map(m=>`<article class="route-card"><div class="route-top"><span aria-hidden="true">${m.icon}</span><small>${m.minutes} ${tr('min')}${answered(m)?.selected===m.right?' · ✓':''}</small></div><h2>${tx(m.title)}</h2><p>${tx(m.lead)}</p><a class="text-button" href="workshop.html?topic=${m.id}" data-topic="${m.id}">${tr('open')} →</a></article>`).join('')||`<p class="empty-state">${tr('empty')}</p>`;
  }
  function route(m){
    const a=answered(m),index=W.modules.indexOf(m),next=W.modules[(index+1)%W.modules.length];
    $('#routeDetail').hidden=false;
    $('#routeDetail').innerHTML=`<a class="text-button" href="workshop.html" data-topic="">← ${tr('back')}</a><article class="route-reading"><div class="eyebrow">${m.icon} · ${m.minutes} ${tr('min')}</div><h2 tabindex="-1" id="routeTitle">${tx(m.title)}</h2><p class="route-lead">${tx(m.lead)}</p><div class="reading-sections">${['idea','example','limit'].map((key,i)=>`<section><span class="reading-number">0${i+1}</span><h3>${tr(key)}</h3><p>${tx(m[key])}</p></section>`).join('')}</div><section class="route-task"><div class="eyebrow">${tr('task')}</div><h3>${tx(m.task)}</h3><label class="confidence-label" for="confidence">${tr('confidence')}</label><select id="confidence" ${a?'disabled':''}>${['low','mid','high'].map(k=>`<option value="${k}" ${a?.confidence===k?'selected':''}>${tr(k)}</option>`).join('')}</select><div class="case-options">${m.options.map((o,i)=>`<button type="button" class="case-option${a&&i===m.right?' correct':''}${a&&a.selected===i&&i!==m.right?' wrong':''}" data-answer="${i}" ${a?'disabled':''}>${tx(o)}</button>`).join('')}</div><div class="route-feedback" role="status">${a?`<strong>${tr(a.selected===m.right?'correct':'wrong')}</strong><p>${tx(m.why)}</p>${a.confidence==='high'&&a.selected!==m.right?`<p>${tr('calibration')}</p>`:''}<button type="button" class="text-button" id="retryRoute">${tr('retry')}</button>`:''}</div></section><section class="reading-note"><label for="readingNote">${tr('note')}</label><textarea id="readingNote" rows="4" maxlength="4000"></textarea><small id="noteStatus" role="status"></small></section><details class="route-references" open><summary>${tr('references')}</summary><ul>${m.sources.map(s=>`<li>${link(s.url,s.title)}</li>`).join('')}</ul></details><details class="route-references"><summary>${tr('books')} · ${m.books.length}</summary><ul>${m.books.map(id=>{const b=K.books.find(b=>b.id===id);return b?`<li><a href="books.html#${b.id}">${escape(b.title)}</a> — ${escape(b.author)||'—'}</li>`:''}).join('')}</ul></details><div class="concept-links" aria-label="${tr('concepts')}">${m.concepts.map(id=>{const c=K.concepts.find(c=>c.id===id);return c?`<a href="concepts.html#${id}">${tx(c.title)}</a>`:''}).join('')}</div><a class="btn primary next-route" href="workshop.html?topic=${next.id}" data-topic="${next.id}">${tr('next')} →</a></article>`;
    $('#readingNote').value=typeof state.notes[m.id]==='string'?state.notes[m.id]:'';
    $('#readingNote').addEventListener('input',e=>{state.notes[m.id]=e.target.value;$('#noteStatus').textContent=tr(save()?'saved':'saveError')});
    $$('[data-answer]').forEach(b=>b.addEventListener('click',()=>{if(answered(m))return;state.answers[m.id]={selected:Number(b.dataset.answer),confidence:$('#confidence').value};const ok=save();route(m);progress();if(!ok)$('#noteStatus').textContent=tr('saveError')}));
    $('#retryRoute')?.addEventListener('click',()=>{delete state.answers[m.id];save();route(m);progress();$('#confidence').focus()});
  }
  function selectRoute(id,push=true){
    active=id;const m=W.modules.find(x=>x.id===id);$('#routeCatalog').hidden=Boolean(m);$('#routeDetail').hidden=!m;
    if(m)route(m);else renderCards();
    if(push){const url=new URL(location.href);if(m)url.searchParams.set('topic',m.id);else url.searchParams.delete('topic');url.hash='';history.pushState({},'',url);if(m)$('#routeTitle').focus();else $('#routeSearch').focus()}
  }
  function slider(id,label,min,max,step,suffix=''){return `<label for="${id}">${label} <output id="${id}Value" for="${id}"></output></label><input id="${id}" data-model="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${sliderState[id]}" aria-describedby="${id}Value">`}
  function renderModels(){
    $('#bayesLab').innerHTML=`<div class="eyebrow">01 · ${tr('workshop')}</div><h2>${tr('bayes')}</h2><p>${tr('bayesText')}</p><div class="model-controls">${slider('prevalence',tr('prevalence'),0,100,1)}${slider('sensitivity',tr('sensitivity'),0,100,1)}${slider('specificity',tr('specificity'),0,100,1)}</div><div id="frequencyOutput" aria-live="polite"></div><p class="knowledge-note">${tr('bayesWhy')}</p>${link('https://pubmed.ncbi.nlm.nih.gov/26528197/','Hoffrage et al. · 2015')}`;
    $('#receptorLab').innerHTML=`<div class="eyebrow">02 · ${tr('workshop')}</div><h2>${tr('receptor')}</h2><p>${tr('receptorText')}</p><div class="model-controls">${slider('concentration',tr('concentration'),0,50,1)}${slider('kd',tr('kd'),1,20,1)}${slider('efficacy',tr('efficacy'),0,1,.1)}</div><div id="receptorOutput" aria-live="polite"></div><p class="knowledge-note">${tr('receptorWhy')}</p><a href="workshop.html?topic=receptors" data-topic="receptors">${tr('open')} →</a>`;
    $$('[data-model]').forEach(el=>el.addEventListener('input',()=>{sliderState[el.id]=Number(el.value);updateModels()}));updateModels();
  }
  function updateModels(){
    for(const [key,value] of Object.entries(sliderState))$('#'+key+'Value').textContent=`${value}${['prevalence','sensitivity','specificity'].includes(key)?'%':''}`;
    const f=M.frequencies(sliderState.prevalence,sliderState.sensitivity,sliderState.specificity),fmt=n=>new Intl.NumberFormat(lang,{maximumFractionDigits:1}).format(n);
    $('#frequencyOutput').innerHTML=`<div class="frequency-grid">${['tp','fp','fn','tn'].map(key=>`<div class="frequency-cell ${key}"><span>${tr(key)}</span><strong>${fmt(f[key])}</strong><div class="frequency-bar" aria-hidden="true"><span style="width:${f[key]/10}%"></span></div></div>`).join('')}</div><div class="model-result"><span>${tr('ppv')}</span><strong>${f.ppv===null?'—':`${fmt(f.ppv*100)}%`}</strong><small>${f.ppv===null?tr('undefined'):`${fmt(f.tp)} / (${fmt(f.tp)} + ${fmt(f.fp)})`}</small></div>`;
    const r=M.receptor(sliderState.concentration,sliderState.kd,sliderState.efficacy);
    $('#receptorOutput').innerHTML=['occupancy','response'].map(key=>`<div class="receptor-meter"><div><span>${tr(key)}</span><strong>${fmt(r[key]*100)}%</strong></div><div class="frequency-bar" aria-hidden="true"><span style="width:${r[key]*100}%"></span></div></div>`).join('');
  }
  function renderActivity(name){
    const run=runs[name],items=A[name],mount=$('#'+name+'Lab'),item=items[run.index],selected=run.answers[run.index],done=run.answers.length===items.length;
    const score=run.answers.filter((value,i)=>value===items[i].right).length;
    mount.innerHTML=`<div class="eyebrow">${name==='consequences'?'03':'04'} · ${tr('workshop')}</div><h2>${tr(name)}</h2><p>${tr(name+'Text')}</p><div class="activity-position">${run.index+1}/${items.length} · ${score}/${run.answers.length}</div><h3>${tx(item.q)}</h3><div class="case-options">${item.options.map((o,i)=>`<button type="button" class="case-option${selected!==undefined&&i===item.right?' correct':''}${selected===i&&i!==item.right?' wrong':''}" data-option="${i}" ${selected!==undefined?'disabled':''}>${tx(o)}</button>`).join('')}</div><div class="case-feedback" role="status">${selected===undefined?'':`<strong>${tr(selected===item.right?'correct':'wrong')}</strong><p>${tx(item.why)}</p>`}</div>${selected!==undefined?`<button type="button" class="btn primary" data-next>${tr(done?'restart':'nextCase')}</button>`:''}${done?`<p role="status">${tr('result')}: ${score}/${items.length}. ${tr('completed')}</p>`:''}<p><a href="workshop.html?topic=${name==='interview'?'interview':'consequences'}" data-topic="${name==='interview'?'interview':'consequences'}">${tr('open')} →</a></p>`;
    mount.querySelectorAll('[data-option]').forEach(b=>b.addEventListener('click',()=>{if(run.answers[run.index]!==undefined)return;run.answers[run.index]=Number(b.dataset.option);renderActivity(name)}));
    mount.querySelector('[data-next]')?.addEventListener('click',()=>{if(done){run.index=0;run.answers=[]}else run.index++;renderActivity(name);mount.querySelector('h3').setAttribute('tabindex','-1');mount.querySelector('h3').focus()});
  }
  function render(){
    document.title=`${tr('workshop')} — ${tx(K.ui[lang]?{[lang]:K.ui[lang].brand}:{ru:'Это сложнее'})}`;
    $$('[data-w18n]').forEach(el=>el.textContent=tr(el.dataset.w18n));
    $('#routeSearch').placeholder=tr('search');$('#routeSearch').setAttribute('aria-label',tr('search'));
    $('#routeFilters').innerHTML=`<button type="button" class="knowledge-chip${domain==='all'?' active':''}" data-route-domain="all" aria-pressed="${domain==='all'}">${tr('all')}</button>`+K.domains.filter(d=>W.modules.some(m=>m.domain===d.id)).map(d=>`<button type="button" class="knowledge-chip${domain===d.id?' active':''}" data-route-domain="${d.id}" aria-pressed="${domain===d.id}">${tx(d.label)}</button>`).join('');
    $$('[data-route-domain]').forEach(b=>b.addEventListener('click',()=>{domain=b.dataset.routeDomain;render()}));
    selectRoute(active,false);progress();renderModels();renderActivity('consequences');renderActivity('interview');
  }
  $('#routeSearch').addEventListener('input',e=>{search=e.target.value;renderCards()});
  $('#resetFilters').addEventListener('click',()=>{domain='all';search='';$('#routeSearch').value='';render()});
  document.addEventListener('click',e=>{const a=e.target.closest('a[data-topic]');if(!a||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button!==0)return;e.preventDefault();selectRoute(a.dataset.topic)});
  window.addEventListener('popstate',()=>selectRoute(new URLSearchParams(location.search).get('topic')||'',false));
  $('#languageSelect').addEventListener('change',e=>{lang=e.target.value;render()});
  render();
})();
